### ISSUE TITLE
Controlar suspensão de bolsas

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#100]
Alunos de doutorado que saem para o sanduíche têm suas bolsas suspensas pelo período do sanduíche. Quando eles voltam, suas bolsas são reativadas. Isso ainda não está sendo controlado pelo SAPOS. Seria interessante poder "suspender" uma bolsa por um número X de meses, e cadastrar uma notificação, passado o término desse período, para lembrar o coordenador de reativar a bolsa.

**Comment by leomurta** [comment]
Tenho a impressão de que seria melhor isso ficar na tela da bolsa ou do aluno, e não na tela de alocação. Isso pq praticamente nunca operamos na tela de alocação. O que acham?

**Comment by leomurta** [comment]
Outra coisa: será que essa flag de active é de fato necessária os só está trazendo confusão?

**Comment by leomurta** [comment]
Por fim, na visualização da ficha do aluno não aparece nada sobre a suspensão. Não deveria aparecer?
