### ISSUE TITLE
Nomes de colunas das consultas

### ISSUE THREAD

**Issue by emoreth** [gems-uff/sapos#131]
Atualmente não há restrições quanto ao nome das colunas em uma query, sendo assim, nem todas as queries válidas geram identificadores válidos para variáveis no mapeamento direto dos nomes das colunas.

Deve ser alterada a DSL das queries para permitir que valores não normalizados sejam inseridos nos templates.

**Comment by braganholo** [comment]
Testei essa issue modificando uma consulta já existente, adicionando um AS "email do aluno", assim:

SELECT students.email AS "email do aluno", 
	students.name AS name, 
	due_date AS due_date
FROM phase_completions 
	INNER JOIN enrollments ON enrollments.id = phase_completions.enrollment_id 
	INNER JOIN students ON students.id = enrollments.student_id
WHERE completion_date<=:data_consulta
AND enrollments.id NOT IN (SELECT dismissals.enrollment_id from dismissals)
AND phase_completions.phase_id = 1
AND enrollments.enrollment_status_id = 2

Ao tentar salvar, o SAPOS emite um erro "NoMethodError: undefined method `query' for nil:NilClass: ROLLBACK"

Mas de qq maneira, apesar do erro, ele salva a alteração e consegue simular a consulta normalmente, gerando uma coluna com esse título "email do aluno".

**Comment by emoreth** [comment]
Este erro "NoMethodError: undefined method query" foi corrigido no ticket #182
