### ISSUE TITLE
Atualizar ruby

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#144]
As páginas da wiki sugerem usar o ruby 1.9.3, mas essa versão não é mais suportada desde fevereiro e as versões mais novas receberam correções de segurança. 
A versão estável mais nova é a 2.1.2 e ela parece ter mantido grande parte da compatibilidade.
Acho que vale a pena testar o sapos nessa versão, e se estiver tudo ok, atualizar a wiki (e o servidor)

**Comment by leomurta** [comment]
Instalei o RVM na conta do sapos e agora estamos usando o Ruby 2.2.0.
