### ISSUE TITLE
Retirar abas para usuário com perfil desconhecido

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#146]
Quando um usuário que tem perfil "desconhecido" se loga, aparecem 3 abas (disciplinas e outras duas). Ao clicar em uma dessas abas, a aplicação lança um erro (something went wrong). Seria bom fazer com que essas 3 abas não apareçam mais, para evitar esse erro.

**Comment by danielpcampagna** [comment]
Existem 3 abas (Disciplinas, Formação, Logout). Dessas, o erro ocorre nas abas Disciplina e Formação. Deve ficar apenas Logout?

**Comment by JoaoFelipe** [comment]
Por curiosidade, por que um usuário teria o perfil desconhecido? Será que não é melhor tirar esse tipo de usuário?

**Comment by braganholo** [comment]
Sim Daniel, deve ficar apenas a aba de Logout. 

João, o perfil desconhecido é útil em casos em que o usuário tinha permissão e agora não tem mais. Por exemplo, quando um professor é descredenciado, passamos o perfil dele para desconhecido. Assim ele não tem mais acesso ao sistema, mas seu usuário e senha continuam lá no SAPOS. Quando ele se recredenciar, basta mudarmos o perfil dele para professor novamente, e tudo está resolvido.

**Comment by danielpcampagna** [comment]
Vanessa, quanto ao usuário do tipo Aluno, quais abas devem aparecer?
Antes da correção dessa issue, eram as mesmas do usuário Desconhecido.

**Comment by braganholo** [comment]
Continuam sendo as mesmas do perfil desconhecido, pois o sistema ainda não
está preparado para lidar com alunos usuários.

**Comment by braganholo** [comment]
Ao invés de aparecer apenas a aba de logout, aparece um erro "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

Além disso, ele envia um email de excessão dizendo que houve tentativa de acesso não autorizada (ver emails enviados pelo SAPOS no dia 27/03 de 18:17h até 18:20h.
