### ISSUE TITLE
Reordenar campos na edição de matrícula

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#147]
A nova ordem deve ser

- dados da matrícula
- orientadores
- bolsas
- Realização de etapa
- Prorrogação
- Trancamento
- inscrições
- banca
- desligamento

**Comment by danielpcampagna** [comment]
Isso deve ser feito apenas na página de edição?

**Comment by braganholo** [comment]
Na visualização também

**Comment by braganholo** [comment]
Na visualização as conclusões de etapas ainda aparecem fora de ordem (estão aparecendo no final da página)
