### ISSUE TITLE
Atualizar texto descritivo de uso de variáveis na tela de notificações

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#152]
Adicionar explicação para uso de atributo isolado.
Exemplo: <%= var('name') %>

**Comment by braganholo** [comment]
Essa string está sendo cortada:
<% records.each do |record| %>

**Comment by leomurta** [comment]
Que loucura. O Github fechou novamente a issue baseado na mensagem de um commit velho, só pq eu dei merge dele no master. Vejam que o próprio commit e6006c5 aparece como feito agora, mas ele foi feito faz tempo.

**Comment by JoaoFelipe** [comment]
Parece que o github só fecha issues quando os commits vão para o master:
https://help.github.com/articles/closing-issues-via-commit-messages/

```
... For example, a commit message with Fixes #45 will close issue 45 in that repository once the commit is merged into the default branch.

If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip.
```

**Comment by leomurta** [comment]
Interessante João!!

**Comment by braganholo** [comment]
Essa string continua cortada no texto explicativo: 
<% records.each do |record| %>

Talvez a solução seja colocar essa explicação acima do campo "Template do Corpo", e não ao lado.

**Comment by emoreth** [comment]
Corrigido na migracao do rails
