### ISSUE TITLE
Erro ao alterar consulta

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#156]
Se eu altero uma consulta de forma a precisar adicionar mais parâmetros a ela, ele diz que salva os novos parâmetros mas não salva. Além disso, ao tentar executar a consulta, dá internal error. Note que não existe nenhuma notificação atrelada a essa consulta.

**Comment by leomurta** [comment]
Everton, pela sua mensagem de commit essa issue não foi solucionada por completo, certo? A solução seria migrar para Rails 4.2? Quão complicado seria essa migração?
