### ISSUE TITLE
Ano de turmas novas

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#163]
O SAPOS não permite que eu crie uma turma de 2015. O ano mais recente que aparece no combo box onde seleciono o ano em que a turma vai ser oferecida é 2014. Isso me impede de montar o quadro de horários do período que vem, e isso já está sendo feito agora. Portanto a correção disso é urgente.

**Comment by danielpcampagna** [comment]
Quando o erro ocorre?

**Comment by braganholo** [comment]
O erro ocorre ao clicar no botão Adicionar da tela de Turmas.
