### ISSUE TITLE
Impressão do Quadro de Horários

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#164]
Colocar o valor da variável class_schedule_text, além do aviso sobre "horário a combinar" apenas uma vez, no final da emissão do quadro de horários. Isso atualmente aparece em todas as páginas, o que polui o quadro desnecessariamente.

**Comment by braganholo** [comment]
Agora está dando erro ao gerar a pauta. "We're sorry, but something went wrong."

**Comment by danielpcampagna** [comment]
Vanessa, existe alguma diferença entre código que está rodando na civil e o que está na computação?
Pois esse erro ocorre apenas na computação.

**Comment by braganholo** [comment]
Sim, existe. A que está rodando na civil é a 4.2, e a que está rodando
no nosso servidor de homologação é a 4.2.0-52-g51b9ec2. Olhe sempre no
canto superior direito da tela. Lá tem o número da versão que está
rodando.

**Comment by braganholo** [comment]
@emoreth por favor veja isso. Pode ser efeito colateral da atualização do Rails ou de algum componente.

**Comment by braganholo** [comment]
Apenas para registrar, o problema está acontecendo com qualquer PDF (histórico, boletim, ou relatório de resultados de consultas)

**Comment by danielpcampagna** [comment]
Eu tentei simular o erro no sapos local. Para isso, apenas precisei mudar a gem prawn da versão 0.15.0 para a 2.0.1.

**Comment by danielpcampagna** [comment]
As soluções que encontrei foram: voltar para a versão 0.15.0 ou instalar a gem prawn-table. Optei pela segunda, deu certo. Porém quando fui testar a issue #187, ele me gerou a seguinte mensagem: 

Document#transaction has been disabled because its implementation lead to corrupted documents whenever a page boundary was crossed. We will try to work on reimplementing it in a future release

**Comment by braganholo** [comment]
@emoreth, alguma ideia do que fazer? Precisamos resolver isso com urgência. Essa versão tem várias coisas importantes que não estão entrando em produção por que esse erro é impeditivo.

**Comment by emoreth** [comment]
Acho que resolveu, mas por favor faça um teste com o aluno que estava dando problema.

**Comment by leomurta** [comment]
Coloquei em homologação.

**Comment by danielpcampagna** [comment]
Já pode ser fechada?

**Comment by leomurta** [comment]
Não Daniel. Deu problema e Everton está trabalhando sobre isso. Como tinham dados sensíveis, Vanessa passou os exemplos de problemas por e-mail direto para o Everton.

**Comment by braganholo** [comment]
Continuamos com o erro "We're sorry, but something went wrong." ao gerar PAUTAS, QUADRO DE HORÁRIOS (na tela de turmas), RELATÓRIOS DE BOLSAS (na tela de bolsas),

**Comment by braganholo** [comment]
O Quadro de Horários e o Relatório de bolsas estão sendo gerados sem o ".pdf" no final do nome do arquivo. Além disso, ao gerar a pauta de 2014/2, o rodapé não saiu. Todos os outros testes que fiz estavam perfeitos, mas no quadro de horários de 2014/2 não aparece o rodapé (mensagem de horário a combinar e o texto da variável "class_schedule_text".

**Comment by braganholo** [comment]
O erro do "We're sorry, but something went wrong." voltou ao gerar o Quadro de Horários. Ele acontece quando um determinado número de disciplinas é incluído no quadro. No momento atual, se eu adiciono uma turma a mais ele passa a dar erro. Se retiro essa turma, ele volta a funcionar. Mas... preciso adicionar 3 turmas ainda no QH...

**Comment by braganholo** [comment]
Investigando um pouco a questão, descobrimos que o problema está sendo gerado por disciplinas que estão sem horário definido. Por exemplo, disciplina de Estudo Orientado nunca tem horário, e era gerada com um asterisco em cada coluna de horário no QH. Para mitigar o problema momentaneamente, editei o tipo de disciplina e pedi para Estudo Orientado e também Estágio em Docência (que cai na mesma situação), não aparecerem no QH. De qq maneira, já sabemos que o problema está nesses asteriscos, de alguma forma...

**Comment by tiagoamaro** [comment]
@braganholo, a sua afirmação está correta. O problema está na impressão de disciplinas que não possuem nenhum horário (`allocations`).

Consigo replicar o erro em ambiente de desenvolvimento criando uma turma sem alocações.

Pelo que entendi do código atual, o comportamento seria imprimir um asterisco no lugar dos horários/sala para disciplinas que não possuem horários definidos, correto?

Esse bug pode ser corrigido simplesmente removendo [essa linha de código](https://github.com/gems-uff/sapos/blob/edd6415bf289e4da7c8d5c8c7d4558470a9032b7/app/helpers/course_classes_pdf_helper.rb#L155), já que a largura da tabela em relação aos dias da semana [já é definido em outro lugar](https://github.com/gems-uff/sapos/blob/edd6415bf289e4da7c8d5c8c7d4558470a9032b7/app/helpers/course_classes_pdf_helper.rb#L131).

Quer que eu abra um PR com a correção para ser testada em homologação?

**Comment by leomurta** [comment]
@tiagoamaro, abra sim por favor, baseado no ramo bugfixes. Obrigado!

**Comment by leomurta** [comment]
Obrigado Tiago! Funcionou perfeitamente!

**Comment by tiagoamaro** [comment]
:smiley: :+1:
