### ISSUE TITLE
Não é possível criar duas disciplinas com o mesmo nome

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#166]
Mesmo que a disciplina que está sendo criada seja do currículo atual e a antiga não, o SAPOS não permite criar duas disciplinas com o mesmo nome -- deveria permitir.

**Comment by danielpcampagna** [comment]
Caso o currículo seja o mesmo, ainda assim deve ser permitido criar duas disciplinas com o mesmo nome?

**Comment by leomurta** [comment]
Nesse caso não, Daniel.
