### ISSUE TITLE
Atualizar active_scaffold para 3.4.14

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#167]
Tem várias correções referentes a forms e subforms que provavelmente irão corrigir o bug da issue #47

**Comment by emoreth** [comment]
Atualizado para 3.4.18.1 em 9e8ce8a35e68d8e603b073bf0ad4dfa36d2c4819

**Comment by emoreth** [comment]
Fica faltando adequaçao do servidor para podermos fazer o deploy, já que agora a versão do uby deve ser atualizada.

**Comment by leomurta** [comment]
Lembrete para mim mesmo: instalar Ruby 2.2.1 no servidor.

**Comment by leomurta** [comment]
@emoreth, consegui instalar o RVM no servidor, e em seguida instalei o Ruby 2.2.0, que é o mais recente disponível. Na terça podemos tentar colocar o Sapos usando essa nova versão do Ruby.

**Comment by emoreth** [comment]
Estranho, acabei de conseguir instalar o ruby 2.2.1 num debian "virtual" aqui. mas acho que deve funcionar com o 2.2.0 tbm. Vou fazer o teste.

**Comment by leomurta** [comment]
O que aparece aqui para mim é o seguinte:
# MRI Rubies
[ruby-]1.8.6[-p420]
[ruby-]1.8.7[-head] # security released on head
[ruby-]1.9.1[-p431]
[ruby-]1.9.2[-p330]
[ruby-]1.9.3[-p551]
[ruby-]2.0.0[-p598]
[ruby-]2.1.4
[ruby-]2.1[.5]
[ruby-]2.2.0
[ruby-]2.2-head
ruby-head

**Comment by braganholo** [comment]
Os campos record select pararam de funcionar. Isso provavelmente foi causado por essa atualização. Estou reabrindo essa issue para que vcs verifiquem.

**Comment by leomurta** [comment]
Vi que saiu o Ruby 4.2.1. Não valeria a pena aproveitar para atualizar para ele?

**Comment by leomurta** [comment]
Saiu tb o Active Scaffold 3.4.19. Poderia tb aproveitar para atualizar para esse.

**Comment by emoreth** [comment]
Gems Rails, active-scaffold e outras atualizadsa.

**Comment by leomurta** [comment]
Avise quando for para colocar novamente em homologação, por favor.

**Comment by emoreth** [comment]
Acho que agora podemos colocar em homologacao.

**Comment by leomurta** [comment]
Coloquei em homologação para @braganholo testar.

Notei que tem dois gems que vêm do seu github (https://github.com/emoreth/clamsy.git e https://github.com/emoreth/carrierwave-activerecord.git). O que seria? Não tem como usarmos a versão deles, que seria beneficiada com bugfixes, etc.?

**Comment by emoreth** [comment]
Na verdada a minha versao é que tem os bugfixes... Mas ambos tem pull-request para os repositorios oficiais... Estou so esperando mergearem (se é que vai acontecer... a clamsy é bem antiga por exemplo).

Talvez fosse interessante eu passar os repos para o gems-uff .

**Comment by leomurta** [comment]
Pode ser. Como vc acha melhor fazermos? Eu faço clone do repositório original, vc cadastra o do gems-uff como remote e dá um push para lá? Aí descarta o atual e passa a clonar de lá? Se sim, me passa qual ramo vc fez clone nos repositórios originais.

**Comment by emoreth** [comment]
Existe a opção de se transferir um repositório por completo, sem precisar de pulls e pushs.
Mas preciso de algumas permissoes a mais para poder fazer isso.
Podemos fazer isso hoje de tarde, quando eu chegar ai.

**Comment by braganholo** [comment]
Record select continua não funcionando.

**Comment by emoreth** [comment]
Para mim, todos eles continuam funcionando... Pode me dar um exemplo ? Ou um print ?

**Comment by braganholo** [comment]
![image](https://cloud.githubusercontent.com/assets/1494494/7275911/e8943f60-e8dc-11e4-8ce5-6701315366a5.png)

**Comment by leomurta** [comment]
Era um problema na geração dos assets. Agora está ok.
