### ISSUE TITLE
Formato da data de nascimento no histórico e boletim

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#168]
A data de nascimento no histórico e boletim aparecem como YYYY-MM-DD, e a reitoria diz que isso causa confusão entre mês e dia de nascimento. Solicitaram que fosse alterado para DD/MM/YYYY.

**Comment by danielpcampagna** [comment]
No arquivo Relatório de Matrículas, a data de admissão e desligamento também aparecem no formato YYYY-MM-DD. Elas também devem ficar no formato DD/MM/YYYY?

**Comment by braganholo** [comment]
Sim.

Em quarta-feira, 28 de janeiro de 2015, danielpcampagna <
notifications@github.com> escreveu:
