### ISSUE TITLE
Etapa não pode ser excluída

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#169]
Criei uma etapa, mas vi que não seria necessária. Não cadastrei essa etapa como completa em nenhum aluno. No entanto, quando peço para excluir a etapa, o SAPOS diz "Não é possível excluir Entrega Versão Final". Creio que isso se deva ao fato de que a data para conclusão da etapa é calculada e salva em algum lugar, e não está com delete cascade.

**Comment by JoaoFelipe** [comment]
Acho que entendi o erro:

Ao remover Phase (etapa), o rails usa o dependent => :destroy para remover PhaseCompletion (que armazena prazos das etapas) e PhaseDuration (duração de etapa), nessa ordem.
O dependent => :destroy funciona parecido com o delete cascade, mas ele chama o método destroy de cada objeto desses ao invés de simplesmente deletá-los. Inicialmente, todos os PhaseCompletion são removidos. 

Em seguida, ao mandar remover PhaseDuration, o callback :create_phase_completions de after_commit é chamado e novos PhaseCompletion são criados. Quando o rails tenta calcular a data dos novos PhaseCompletion, já não existe o PhaseDuration que os originou, causando o erro na hora de remover. 

Depois disso tudo, Phase e seus antigos PhaseDuration e PhaseCompletion foram removidos, mas os PhaseCompletion novos foram mantidos com erro de integridade referencial.

Ao tentar ler esses PhaseCompletion na matrícula, ocorrem os erros #170 e #171 

Acho que a solução pra isso vai ser evitar que o after_commit do phase_duration.rb execute no destroy e criar uma uma migration para remover os erros de integridade referencial existentes.

A migration é simples:
```ruby
PhaseCompletion.includes(:phase).where(Phase.arel_table[:name].eq(nil)).destroy_all
```

Ainda não sei como alterar o after_commit para não ocorrer no destroy, eu usava after_save.
Vou tentar procurar isso depois do almoço.
@danielpcampagna, sabe dizer a diferença?

**Comment by JoaoFelipe** [comment]
Acho que está corrigido, tentei executar os testes, mas todos os testes de notificações e um de prorrogação falharam. Não sei há quanto tempo está assim... 
Os de notificações já estavam quebrados desde que @emoreth separou as consultas, o outro não tenho certeza se fui eu. Verifiquem se as prorrogações estão ok durante a homologação

**Comment by braganholo** [comment]
Pode colocar em homologação?

**Comment by JoaoFelipe** [comment]
Pode

**Comment by leomurta** [comment]
João, acho que vc fez no ramo errado. O ramo corretivo atual é o 4.1.x. O @emoreth fez commits equivocados no 4.0.x, que já está descontinuado, e ficou de migrar, mas ainda não o fez. Isso deve ter induzido vc ao erro. Vc poderia, por favor, fazer um merge do ramo 4.0.x para o 4.1.x e depois testar?

**Comment by JoaoFelipe** [comment]
Fiz o merge. Acabou migrando também o que o @emoreth fez.
Esta correção está funcionando. Não cheguei a testar a do Everton

Antes de fazer o merge, executei 'rake spec' e percebi que o test de prorrogação já tava falhando antes. Mas acho que é bom testar de qualquer forma se está tudo ok

Pode colocar em homologação

**Comment by leomurta** [comment]
Não estou conseguindo colocar em homologação. Veja o erro na hora da migração:

rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/execjs-2.2.2/lib/execjs/runtimes.rb:51:in `autodetect'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/execjs-2.2.2/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/execjs-2.2.2/lib/execjs.rb:4:in `<top (required)>'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/uglifier-2.1.1/lib/uglifier.rb:3:in `require'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/uglifier-2.1.1/lib/uglifier.rb:3:in `<top (required)>'
/usr/local/sapos/computacao/staging/config/application.rb:10:in `<top (required)>'
/usr/local/sapos/computacao/staging/Rakefile:4:in `require'
/usr/local/sapos/computacao/staging/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
Compiling assets.
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/execjs-2.2.2/lib/execjs/runtimes.rb:51:in `autodetect'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/execjs-2.2.2/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/execjs-2.2.2/lib/execjs.rb:4:in `<top (required)>'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/uglifier-2.1.1/lib/uglifier.rb:3:in `require'
/usr/local/sapos/computacao/staging/vendor/bundle/ruby/1.9.1/gems/uglifier-2.1.1/lib/uglifier.rb:3:in `<top (required)>'
/usr/local/sapos/computacao/staging/config/application.rb:10:in `<top (required)>'
/usr/local/sapos/computacao/staging/Rakefile:4:in `require'
/usr/local/sapos/computacao/staging/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by JoaoFelipe** [comment]
Parece que na atualização para o rails 4, Everton tirou a gem therubyracer,
que executava js.
Vou ver se existe alguma incompatibilidade dela com o rails 4 para ele ter
tirado.

**Comment by leomurta** [comment]
O mais prático pode ser reverter os commits dele, ficando só os seus.

  Leo

On Friday, February 6, 2015, João Felipe N. Pimentel <
notifications@github.com> wrote:

> Parece que na atualização para o rails 4, Everton tirou a gem therubyracer,
> que executava js.
> Vou ver se existe alguma incompatibilidade dela com o rails 4 para ele ter
> tirado.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/gems-uff/sapos/issues/169#issuecomment-73334801>.
>


-- 
Sent from a mobile device.

**Comment by JoaoFelipe** [comment]
Eu teria que fazer cherry-pick exatamente para onde está a tag 4.1.0, já que a atualização do rails ta na 4.1.x e uns commits de correção de consultas estão na 4.0.x

Não encontrei nenhuma incompatibilidade, pode colocar em homologação

**Comment by leomurta** [comment]
João, agora apareceu o seguinte na hora da migração:
```
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = '...' (removi a chave)

Please ensure you restarted your application after installing Devise or setting the key.
```

**Comment by JoaoFelipe** [comment]
Não tinha visto antes. Fiz o cherry-pick dos meus commits para a 4.1.0 e criei o branch 4.1.0.x

Pode colocar a 4.1.0.x em homologação

**Comment by leomurta** [comment]
Esse novo ramo vai confundir, pois não tem uma semântica definida. Eu reverti o commit de upgrade do rails no antigo ramo 4.1.x, e criei um novo ramo, bugfixes, que será o ramo corretivo à partir de agora.

Coloquei bugfixes em homologação.
