### ISSUE TITLE
Notificações desaparecem do SAPOS

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#172]
Criei uma notificação que deveria ter sido enviada hoje para a secretaria. A notificação não foi enviada. Fui checar, e a notificação SUMIU da base do SAPOS. Já tinha notado que as notificações davam erro e desapareciam, mas essa eu aparentemente tinha conseguido criar com sucesso, e ela sumiu... Isso é bem grave pois não tenho nenhum feedback do sistema. Pode ser que outras tenham sumido e eu nem saiba.

**Comment by braganholo** [comment]
Essa issue aparentemente foi resolvida. Estou fechando no momento. Caso volte a ocorrer, reabro.

**Comment by leomurta** [comment]
Marque em qual versão ela foi resolvida, por favor.
