### ISSUE TITLE
Validação de datas no cadastro de alunos

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#173]
Ao tentar cadastrar um aluno e selecionar a data de nascimento ou de expedição de identidade usando o componente de datas, o SAPOS diz que houve erro na validação das datas. O mesmo ocorre se tentamos digitar as datas. Atualmente estamos sendo obrigados a salvar com as datas em branco (note que deixar as datas em branco deve continuar sendo permitido, pois existem casos em que precisamos cadastrar alunos dos quais não temos essas informações).

**Comment by danielpcampagna** [comment]
Pode colocar em homologação.

**Comment by leomurta** [comment]
Coloquei em homologação.
Vanessa, por favor, também teste a issue #165.

**Comment by braganholo** [comment]
Tudo ok. Pode colocar em produção.
