### ISSUE TITLE
Permitir associação de uma disciplina com MAIS DE UMA área de pesquisa

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#176]
Para acomodar mudanças no currículo, precisamos agora que uma disciplina possa ser associada a mais de uma área de pesquisa.

**Comment by danielpcampagna** [comment]
Devo adicionar o arquivo db/migrate/201502... para realizar o commit?

**Comment by leomurta** [comment]
Não sei se entendi a pergunta, mas o migrate é fundamental. Se eu estiver falando algo óbvio, me avise: o migrate é que migra os dados do esquema antigo para o novo. Sem ele, teríamos que ajustar na mão cada uma das disciplinas, já que elas deixarão de ter o ID da área (chave estrangeira) e passarão a se relacionar com N áreas (no BD surgirá uma nova tabela de relacionamento para fazer o meio de campo). A função desse migrate é justamente fazer automaticamente a migração dos dados. Ele terá que, para cada disciplina, pegar a área existente e colocar essa área no conjunto de áreas. Tente fazer essa migração e colar aqui para vermos. Como isso é propenso a erro, apesar de simples, vou chamar o @JoaoFelipe para palpitar.

**Comment by leomurta** [comment]
Ah, apesar de ser uma issue importante, pode deixar para depois do carnaval! Aproveite esse momento para descansar um pouco!

**Comment by danielpcampagna** [comment]
Desculpe-me. Acho foi a minha pergunta que não ficou tão clara.

Para concluir essa issue, tive que criar um novo arquivo com o nome "201502..." no diretório "db/migrate/", além de editar outros arquivos na pasta "app/".

A minha dúvida é: Devo adicionar também este arquivo de migração que foi criado, quando for realizar o commit? Isto é: "git add db/migrate/201502...". Além, é claro, dos demais arquivos.

**Comment by leomurta** [comment]
Sim, pois sem ele não seria possível migrarmos o BD de produção. A minha dúvida é se essa sua migração "só" altera o esquema ou se ela de fato migra os dados. Mas siga em frente! Qq coisa vc dá outros commits depois ajustando.
