### ISSUE TITLE
Erro na tela de busca de orientação

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#177]
Ao fazer uma busca na tela de Professores/Orientações, o sistema lança Internal Error quando um dos seguintes campos de busca estão preenchidos: matrícula ou nome do orientador.

**Comment by braganholo** [comment]
Aparentemente o campo enrollments.id gera o erro porque a tabela enrollments não está no FROM da consulta. Se enrollments não estiver no FROM, o correto aqui seria advisements.enrollment_id. No entanto, quando a consulta envolve o número da matrícula não tem jeito: tem que adicionar a tabela enrollment no FROM.

**Comment by danielpcampagna** [comment]
Caso o aluno tenha um coorientador, ele não pode ter um orientador principal?
O check-box "Orientador Principal" poderá ser marcado, caso o aluno tenha um coorientador?

**Comment by braganholo** [comment]
Mesmo quando há um co-orientador, é obrigatório que um deles esteja marcado
como orientador principal. Pode haver no máximo um orientador principal, e
é obrigatório que, se houver algum orientador cadastrado, um deles seja o
orientador principal (a outra opção é a matrícula não estar associada a
nenhum orientador).
