### ISSUE TITLE
Bancas

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#178]
Na aba Professores, adicionar uma aba lateral Bancas, onde eu possa pesquisar por um determinado professor e ver todas as bancas das quais ele participou.

**Comment by leomurta** [comment]
Mas o SAPOS tem os dados de Bancas? Ou seja, é só uma questão de adicionar uma busca na interface ou é a introdução de um novo conceito no sistema?

**Comment by braganholo** [comment]
É só adicionar a aba e a busca. A informação de banca atualmente só aparece na tela de matrícula.

**Comment by braganholo** [comment]
A entidade no SAPOS se chama thesis_defense_committee_participations

**Comment by leomurta** [comment]
Nossa... estou por fora então. Nem lembrava que tínhamos isso.

**Comment by braganholo** [comment]
O record select na tela de busca não está funcionando. Se eu digito parte do nome do professor no campo de busca por professor, a combo não filtra os nomes dos professores. Isso provavelmente tem relação com a atualização do Active Scaffold (issue #167), mas vou reabrir essa aqui só para garantir. O restante está ok.

**Comment by leomurta** [comment]
Com o tratamendo da issue #167 isso deve ter sido resolvido.
