### ISSUE TITLE
Erro ao usar o botão de busca na tela de Matrícula, em homologação

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#181]
O botão de busca em matrícula no ambiente de homologação não está funcionando. Dá internal error. Início do email de descrição do erro:

A ActionView::Template::Error occurred in enrollments#show_search:

  wrong number of arguments (1 for 0)
  app/helpers/scholarship_durations_helper.rb:134:in `level_search_column'

-------------------------------
Request:
-------------------------------

  * URL       : https://sel.ic.uff.br/sapos-homologacao/enrollments/show_search?adapter=_list_inline_adapter
  * IP address: 200.20.15.54
  * Parameters: {"adapter"=>"_list_inline_adapter", "controller"=>"enrollments", "action"=>"show_search"}
  * Rails root: /usr/local/sapos/computacao/staging
  * Timestamp : 27/03/2015 18:24

(ver email completo enviado pelo SAPOS no dia 27/03 às 18:24h)

**Comment by braganholo** [comment]
Esse bug impede que qualquer coisa seja colocada em produção, já que essa tela de busca é essencial.

**Comment by danielpcampagna** [comment]
Vanessa, caso seja possível, você poderia testar a busca dos campos Tipo de Bolsa e Nível do scholarship_durations? É possível que o erro dessa issue tenha a mesma causa desse.
Não estou conseguindo ter acesso ao Sapos.

**Comment by leomurta** [comment]
Daniel, a homologação está travada com uma release que estamos para fazer com contribuições do @emoreth. Everton, por favor, faça um merge de bugfixes para master para podermos testar isso assim que tivermos a homologação ok. Vou fechar essa issue só para @braganholo lembrar de testar. Se continuar com problema ela reabre.
