### ISSUE TITLE
Erro em homologação no envio de notificação

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#182]
NoMethodError: undefined method `query' for nil:NilClass: ROLLBACK
  app/models/notification.rb:117:in `update_next_execution!'

(ver email de log do SAPOS enviado no dia 3/4/2015 às 6:26h)

**Comment by emoreth** [comment]
Acho que finalmente corrigi este erro. Agora a aplicacao nao desconecta mais a conexao default do rails ao executar a query. Acho que nao vai dar mais problema.

**Comment by braganholo** [comment]
Agora está dando erro na simulação da homologação.

**Comment by emoreth** [comment]
Pelo que eu entendi nos emails de erro isso está acontecendo porque o banco de dados __staging_read_only__ nao está definido.

Vou alterar o código para que isso não seja obrigatório.

**Comment by leomurta** [comment]
Everton,

  Mas o banco de dados staging_read_only está definido sim!

  Leo

2015-05-24 11:20 GMT-03:00 Everton Moreth <notifications@github.com>:

**Comment by leomurta** [comment]
O que acontecerá se vc fizer esse bd read only não ser requerido? As
queries não rodarão ou rodarão no bd read/write? Se for a segunda opção,
não é bom, pois abriria uma brecha de segurança.

  Leo

2015-05-24 11:55 GMT-03:00 Leonardo Murta <leomurta@gmail.com>:
