### ISSUE TITLE
Quebra de página errada no boletim de aluno com muitas disciplinas 

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#187]
Tivemos um caso de boletim gerado errado pelo SAPOS. O aluno em questão cursou muitas disciplinas, e um dos quadros "resumo do período" pulou para a segunda página. Nessa segunda página, ficou apenas esse quadro, e o rodapé no pé da página. Na terceira página, apareceram a caixa de total (carga horária e CR), os orientadores, etapas, etc. Ver imagem com um pedaço da página 1 e página 2 do boletim. Tenho o PDF caso alguém queira verificar maiores detalhes. 

![captura de tela 2015-05-13 as 17 48 53](https://cloud.githubusercontent.com/assets/1494494/7620759/624515a2-f998-11e4-840b-73f870bad827.png)

**Comment by danielpcampagna** [comment]
Pode me mandar o pdf?

**Comment by braganholo** [comment]
Estou reabrindo pois a correção do #193 voltou com esse erro.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Olá. Fiz alguns testes com boletins no ambiente de desenvolvimento, usando como exemplos alguns boletins que apresentavam erros de quebra de página no ambiente de homologação. Os boletins testados tiveram os mesmos problemas de quebra de página. Fiz modificaçẽs para que os erros de quebra não acontecessem. Aparentemente alguns problemas de caixas que ficavam por cima do rodapé não acontecem mais. A caixa de tese também foi modificada para quebrar em mais de uma página caso seja necessário. Estou fechando por não estar vendo o erro de quebra de página no ambiente de desenvolvimento.
