### ISSUE TITLE
Adicionar nacionalidade no cadastro de país

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#188]
Adicionar um novo campo no cadastro de país, para indicar a nacionalidade de quem nasce naquele país. Exemplo: brasileiro para país Brasil. Usar essa informação no histórico escolar e no boletim, ao invés de usar simplesmente o nome do país onde a pessoa nasceu como nacionalidade.

No histórico, ao invés de aparecer: nacionalidade: Brasil, apareceria nacionalidade: Brasileiro.

**Comment by danielpcampagna** [comment]
Está feito. É preciso apenas corrigir o problema das issues #164 e #187 para que eu possa testar.

**Comment by danielpcampagna** [comment]
É preciso terminar a issue #189, a fim de que os alunos estrangeiros tenham a informação do país de origem (sem que haja a necessidade de cadastrar o estado e a cidade)

**Comment by leomurta** [comment]
Daniel, vi que vc colocou valores iniciais no seeds. Contudo, para os BDs que já existem, esses valores não entrariam. Seria necessário ter isso no migration nesse caso. É possível?

Outra coisa: seria necessário adaptar o histórico tb, para ler desse campo.

**Comment by leomurta** [comment]
Vanessa, será que isso não deveria ser classificado como bug? Repare que "nacionalidade: Brasil" é algo errado, que está sendo corrigido por essa issue.

**Comment by braganholo** [comment]
Leo, sim, acho que seria melhor ficar como bug. Já troquei no GitHub.

Vanessa

2015-06-22 17:15 GMT-03:00 Leonardo Gresta Paulino Murta <
notifications@github.com>:

**Comment by danielpcampagna** [comment]
Tem razão, Leo. Isso não me passou pela cabeça. Assim farei.

**Comment by leomurta** [comment]
Pelo que vi, só falta agora ter essa informação no histórico e no boletim, certo?

**Comment by leomurta** [comment]
Pessoal, não sei qual é a real situação dessa issue. Ela está marcada como 4.3.3, mas está aberta. Vou fechar para Vanessa testar na release 4.3.10.

**Comment by braganholo** [comment]
O cadastro de nacionalidade está ok, mas no boletim e no histórico o valor do campo que está sendo impresso ainda é país ao invés de ser nacionalidade. Por exemplo: Nacionalidade: Peru. O correto seria peruano, que é o que está cadastrado como nacionalidade ligada a esse país.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Posso tentar arrumar essa questão da nacionalidade no boletim e no histórico.

**Comment by braganholo** [comment]
Maravilha Carlos! Siga em frente!

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Fiz modificações para completar as issues #188 e #189. Acredito que estejam funcionando de forma correta. As duas issues estão relacionadas porque, para poder exibir a nacionalidade nos relatórios, foi preciso poder referenciar o país de nascimento diretamente no modelo Student.

**Comment by braganholo** [comment]
Está funcionando para cadastros novos, mas nos cadastros antigos a nacionalidade consta como "não informado" no boletim e histórico. Já vi que se eu alterar o cadastro do aluno, sentando novamente o país, funciona. Seria possível fazer alguma migração para arrumar os registros antigos automaticamente? Ou a secretaria vai atualizando à medida em que precisar gerar os históricos?

**Comment by leomurta** [comment]
Vanessa,

  Sem dúvida é possível fazer isso na migração. Mas minha pergunta virou
outra: como o sapos sabe qual é a nacionalidade de uma pessoa em função do
país? Há uma tabela de "tradução" (ex.: Brasil -> brasileiro)? Se sim, por
que é necessário ter um campo para nacionalidade? Não poderia simplesmente
calcular por demanda, se de fato há uma tabela de tradução? Ou eu entendi
errado?

  Leo

Em 14 de junho de 2017 10:23, Vanessa Braganholo <notifications@github.com>
escreveu:
