### ISSUE TITLE
Naturalidade do estudante não está sendo definida

### ISSUE THREAD

**Issue by danielpcampagna** [gems-uff/sapos#189]
Quando apenas o país, do campo Naturalidade do formulário Aluno, é selecionado, o SAPOS não está salvando/atualizando.

**Comment by danielpcampagna** [comment]
Para solucionar este problema, proponho duas soluções:
1) Criamos uma associação entre Student e Country.
2) O SAPOS forçar o usuário a cadastrar o estado e a cidade do aluno.

**Comment by braganholo** [comment]
Acho que pode ser a alternativa 2.

**Comment by danielpcampagna** [comment]
Então, um possível problema dessa, é que nem todos os países são estruturado como Brasil, que é composto por estados e por cidades - créditos a João.

**Comment by leomurta** [comment]
Pessoal, como ficou essa issue? Alguma novidade de como resolver?

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Fiz modificações para completar as issues #188 e #189. Acredito que estejam funcionando de forma correta. As duas issues estão relacionadas porque, para poder exibir a nacionalidade nos relatórios, foi preciso poder referenciar o país de nascimento diretamente no modelo Student.

**Comment by braganholo** [comment]
Está funcionando para cadastros novos, mas nos cadastros antigos a nacionalidade consta como "não informado" no boletim e histórico. Já vi que se eu alterar o cadastro do aluno, sentando novamente o país, funciona. Seria possível fazer alguma migração para arrumar os registros antigos automaticamente? Ou a secretaria vai atualizando à medida em que precisar gerar os históricos?

**Comment by leomurta** [comment]
Acho que eu entendi o problema: o campo birth_country é novo e contem nil. Com isso ele não consegue saber a nacionalidade do aluno já existente. Vejo duas possíveis soluções:

1) Criar uma nova migração visitando todas as tuplas de student e atribuindo o birth_state.country como sendo o valor de country.
2) Alterar o método nationality() para verificar birth_state.country ou birth_city.state.country quando birth_country for nil.

Notem que isso só é necessário pq o BD não está normalizado. Por que temos que guardar birth_state e birth_country se a partir de birth_city é possível obter ambos? Isso pode complicar a manutenção e levar a possíveis inconsistências nos dados, não?

**Comment by braganholo** [comment]
>
> Notem que isso só é necessário pq o BD não está normalizado. Por que temos
> que guardar birth_state e birth_country se a partir de birth_city é
> possível obter ambos? Isso pode complicar a manutenção e levar a possíveis
> inconsistências nos dados, não?
>
​Isso estava assim antes, mas o problema todo é que em muitos casos não
temos a informação de cidade e estado (para os estrangeiros). Por isso ​é
que esse problema todo estava sendo gerado. Como student só tinha city_id,
para os casos em que só sabíamos o país ele não conseguia salvar a
informação.

**Comment by leomurta** [comment]
Entendido. Dentre as minhas soluções 1 e 2, qual vcs acham melhor?

**Comment by braganholo** [comment]
As duas funcionam. Carlos pode escolher a que preferir.

**Comment by leomurta** [comment]
Sugiro fazer a primeira então, pois faz com que o dado fique mais consistente.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Olá pessoal. 
Quando a mudança não funcionou para registros já existentes, foi falha minha mesmo.  Não percebi a questão e passou nos meus testes porque, quando eu crio um registro novo, preciso escolher um país para poder escolher o estado ou a cidade.  Eu acabei escolhendo colocar a referência de country em student vendo os comentários do Daniel acima. Vendo as tabelas, nem todos os países pareciam ter estados ou cidades definidos. Porém também vi que o sapos permite criar cidades e estados caso eles não estejam definidos. Sobre as possíveis soluções, subi uma versão com o método nationality modificado que eu  estava mexendo. Vou olhar  a solução 1 também.

**Comment by braganholo** [comment]
O importante é que seja possível salvar naturalidade em studen com apenas
país (sem cidade ou estado), pois temos vários casos desses na prática.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Agora deve ser possível fazer assim. Escolher apenas o país para um aluno e ele será salvo
e mostrado como nacionalidade no boletim e histórico.
