### ISSUE TITLE
Retirar abas de "Registros deletados" de perfis sem permissão

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#191]
O controle de acesso está sendo feito corretamente, mas está gerando internal error quando alguém com perfil de professor clicar numa dessas abas de "registros deletados".

**Comment by leomurta** [comment]
No commit 835a20373ed7538af1cb88ea75d26c87946cf52d eu removi manualmente a aba em todos os controles. Queria ter feito isso na superclasse, mas lá a actions deleted_records ainda não existe. Deve ter uma forma mais inteligente de resolver isso, mas enquanto não aparece, fica assim.

**Comment by leomurta** [comment]
@braganholo, pode testar. Está em homologação.

**Comment by braganholo** [comment]
Pode colocar em produção.

**Comment by leomurta** [comment]
Feito.
