### ISSUE TITLE
Adicionar ano/semestre de inscrição em disciplina na visualização de matrícula

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#195]
Na tabela que mostra as inscrições do aluno, na tela de visualização de uma matrícula, falta mostrar o ano/semestre de cada inscrição em disciplina.

**Comment by leomurta** [comment]
Aparentemente essa issue já foi implementada em algum momento, sem ter sido anotada no commit. Acho que foi na issue https://github.com/gems-uff/sapos/issues/347. Acho que nesse commit: https://github.com/gems-uff/sapos/commit/e8b447810619cec4d30e9bfae5931387356cb5e1.
Concorda @braganholo? Se sim, vou fechar e vincular com a versão que saiu esse commit.

**Comment by braganholo** [comment]
Sim, já está ok.
