### ISSUE TITLE
Erro ao buscar por etapa atrasada na tela de busca de matrícula

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#197]
A ActiveRecord::StatementInvalid occurred in enrollments#index:

  Mysql2::Error: Unknown column 'dismissals.date' in 'where clause': SELECT `enrollments`.* FROM `enrollments` INNER JOIN `phase_completions` ON `phase_completions`.`enrollment_id` = `enrollments`.`id` WHERE `phase_completions`.`completion_date` IS NULL AND `phase_completions`.`phase_id` = 1 AND (`phase_completions`.`due_date` < '2015-08-02') AND (`dismissals`.`date` > '2015-08-02' OR `dismissals`.`enrollment_id` IS NULL)
  app/models/enrollment.rb:93:in `with_delayed_phases_on'

-------------------------------
Request:
-------------------------------

  * URL       : https://sel.ic.uff.br/sapos-homologacao/enrollments?utf8=%E2%9C%93&search%5Benrollment_number%5D=&search%5Bstudent%5D=&search%5Blevel%5D=&search%5Benrollment_status%5D=&search%5Badmission_date%5D%5Bday%5D=1&search%5Badmission_date%5D%5Bmonth%5D=&search%5Badmission_date%5D%5Byear%5D=&search%5Bactive%5D=all&search%5Bscholarship_durations_active%5D=&search%5Bprofessor%5D=&search%5Baccomplishments%5D%5Bphase%5D=&search%5Baccomplishments%5D%5Bday%5D=2&search%5Baccomplishments%5D%5Bmonth%5D=7&search%5Baccomplishments%5D%5Byear%5D=2015&search%5Bdelayed_phase%5D%5Bphase%5D=1&search%5Bdelayed_phase%5D%5Bday%5D=2&search%5Bdelayed_phase%5D%5Bmonth%5D=8&search%5Bdelayed_phase%5D%5Byear%5D=2015&search%5Bcourse_class_year_semester%5D%5Bcourse%5D=&search%5Bcourse_class_year_semester%5D%5Byear%5D=&search%5Bcourse_class_year_semester%5D%5Bsemester%5D=&search%5Bresearch_area%5D=&search%5Benrollment_hold%5D%5Bhold%5D=0&commit=Buscar
  * IP address: 177.12.22.180
  * Parameters: {"utf8"=>"✓", "search"=>{"enrollment_number"=>"", "student"=>"", "level"=>"", "enrollment_status"=>"", "admission_date"=>{"day"=>"1", "month"=>"", "year"=>""}, "active"=>"all", "scholarship_durations_active"=>"", "professor"=>"", "accomplishments"=>{"phase"=>"", "day"=>"2", "month"=>"7", "year"=>"2015"}, "delayed_phase"=>{"phase"=>"1", "day"=>"2", "month"=>"8", "year"=>"2015"}, "course_class_year_semester"=>{"course"=>"", "year"=>"", "semester"=>""}, "research_area"=>"", "enrollment_hold"=>{"hold"=>"0"}}, "commit"=>"Buscar", "controller"=>"enrollments", "action"=>"index"}
  * Rails root: /usr/local/sapos/computacao/staging
  * Timestamp : 02/07/2015 09:22

**Comment by braganholo** [comment]
Pelo visto ele usou dismissal no WHERE sem ter definido no FROM.

**Comment by leomurta** [comment]
@JoaoFelipe, dê uma olhada nesse bug por favor. Tentei olhar o código, na parte que acontece o bug: app/models/enrollment.rb:93:in `with_delayed_phases_on'. Aí fiz uma regressão nos commits para ver quando essa parte foi alterada por último, já que isso funcionava no passado. Achei esse seu commit (https://github.com/gems-uff/sapos/commit/0664cc37060276e3583b66a3883f1b9b06a68fb8), onde vc troca http://pastebin.com/PQx1rtxQ por http://pastebin.com/7mkRXQKP.

Olhando rápido, vc consegue perceber o que pode estar havendo?

**Comment by JoaoFelipe** [comment]
Aparentemente isso acontece devido a uma mudança no includes que não
consegue mais detectar referencias no where:
http://blog.arkency.com/2013/12/rails4-preloading/
Imagino que se adicionar .references(:dismissals) na consulta deve resolver
o problema. Estou instalando ruby 2.2.0 e rails aqui para testar.


Sugiro fazer uma busca por todos os locais que consultas com includes foram
feitas e ver se continuam funcionando

João Felipe

Em 4 de julho de 2015 10:52, Leonardo Gresta Paulino Murta <
notifications@github.com> escreveu:

**Comment by JoaoFelipe** [comment]
Era isso mesmo. Pode colocar em homologação.

Fiz uma busca por todo uso da palavra "includes" e parece que essa era a única consulta assim.

**Comment by leomurta** [comment]
Funcionou João. Obrigado.

**Comment by braganholo** [comment]
Obrigada João!
