### ISSUE TITLE
Adicionar extensão .pdf no relatório de matrícula

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#198]
Relatório emitido na tela de busca de matrícula está sem a extensão .pdf.

**Comment by bschettino** [comment]
@braganholo 
Depois que fizerem o deploy e conferirem que está funcionando vocês mesmo fecham as issues?
Mandei pull requests para as issues #205 e #206 também.

**Comment by leomurta** [comment]
Bruno, o que normalmente fazemos é o desenvolvedor fechar para indicar que ele acredita que está tudo ok. Aí, se acharmos algum problema durante o teste, reabrimos. Vou fechar as 3 então. Obrigado.

**Comment by bschettino** [comment]
OK. Na próxima vez eu mesmo fecho então.
