### ISSUE TITLE
Erro no recordselect de Disciplina na criação de turma

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#203]
Há cerca de 1h recebi um erro do sapos em produção.
Provavelmente fui eu que causei esse erro na alteração urgente ao tentar deixar um monkeypatch do recordselect genérico tanto para o mysql quanto para o sqlite.
Aparentemente minha alteração causou bug no mysql.

Quando fiz a alteração, eu criei uma issue no recordselect: https://github.com/scambra/recordselect/issues/12 e desde então já teve a atualização da gem no rubygems com a correção. Imagino que atualizar o recordselect e remover o arquivo https://github.com/gems-uff/sapos/blob/master/config/initializers/recordselect_patch.rb solucione o problema

**Comment by leomurta** [comment]
João, faça isso então e de commit em bugfix. Aí eu coloco em homologação para testarmos. Obrigado.

**Comment by JoaoFelipe** [comment]
Parece que a versão do rubygems está errada/desatualizada. Testei a do git e a correção funcionou.
Comittei uma possível correção voltando o monkeypatch anterior. Assim que o recordselect for realmente atualizado, o arquivo https://github.com/gems-uff/sapos/blob/master/config/initializers/recordselect_patch.rb pode ser removido

**Comment by JoaoFelipe** [comment]
Acabei errando o comando amend (fiz git commit -a ao invés de --amend) e fiz um commit novo atualizando o recordselect e com a mensagem que era para atualizar a anterior. Vou deixar assim mesmo

**Comment by leomurta** [comment]
Coloquei em homologação. Vanessa, pode testar.

**Comment by braganholo** [comment]
Funcionou! Obrigada. Leo, pode colocar em produção.

**Comment by leomurta** [comment]
Coloquei em produção.

**Comment by braganholo** [comment]
Obrigada!

>
