### ISSUE TITLE
Usuários novos não conseguem fazer login

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#204]
Quando crio um usuário, ele recebe um email de confirmação de conta. O email que ele recebe tem dois problemas: 

1) O link vem com sapos/sapos -- um sapos a mais no endereço
2) Mesmo corrigindo o link, ao enviar a URL aparece a mensagem de que o "confirmation token não é válido"

O usuário então não consegue acesso ao sistema. O mesmo ocorre quando se clica em esqueci minha senha. Aqui a mensagem muda para "Reset password token não é válido".

**Comment by leomurta** [comment]
João corrigiu esse problema. Colocamos em homologação. Pode testar.

**Comment by braganholo** [comment]
Está tudo ok. Tem apenas um pequeno detalhe: ao clicar no link de confirmação da conta no email, ele vai pro SAPOS e aparece uma mensagem "Sua conta foi confirmada com sucesso. Você está logado.". No entanto, o usuário não está logado. 

No reset de senha aparece uma mensagem parecida, mas nesse caso ele faz o login do usuário. 

No caso da confirmação de conta, sugiro apenas trocar o "Você está logado" por "Informe seu usuário e senha para fazer login".

**Comment by leomurta** [comment]
Coloquei em homologação novamente. Por favor, veja se agora está ok a mensagem.

**Comment by braganholo** [comment]
Leo, ficou ótimo. Pode colocar em produção.

**Comment by leomurta** [comment]
Coloquei em produção.
