### ISSUE TITLE
Link de visualizar em Configuração de Relatório

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#205]
Ao clicar em "visualizar" no formulário de criação/edição de configuração de relatório (/report_configurations), ocorre o erro:
```
A ActiveModel::ForbiddenAttributesError occurred in report_configurations#preview:

  ActiveModel::ForbiddenAttributesError
  app/controllers/report_configurations_controller.rb:56:in `preview'
```

**Comment by leomurta** [comment]
Bruno, obrigado pelo fix. Só para confirmar: com esse fix, podemos fechar essa issue?
