### ISSUE TITLE
Erro ao imprimir histórico e boletim quando o aluno tem algum trancamento

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#207]
Ao tentar imprimir histórico e boletim de aluno que tem algum trancamento, a seguinte mensagem de erro é lançada aparece: 

A ActionView::Template::Error occurred in enrollments#academic_transcript_pdf:

  Table's width was set too small to contain its contents (min width 560.0, requested 523.28)
  app/helpers/enrollments_pdf_helper.rb:870:in `block in enrollment_holds_table'

**Comment by JoaoFelipe** [comment]
Pode colocar em homologação

**Comment by leomurta** [comment]
Obrigado João!
Coloquei em homologação. @braganholo, pode testar.

**Comment by braganholo** [comment]
A borda superior e lateral da tabela de trancamentos está preta ao invés de azul tanto no histórico quanto no boletim. Além disso, acho que ficaria melhor se fosse como as tabelas de etapas e prorrogações, sem colunas (essas só aparecem no boletim). Poderia aparecer período e duração tudo junto (nas outras aparece data e nome da etapa ou prorrogação, também tudo junto), tanto no histórico quanto no boletim.

Trancamentos
2015/1 1 Semestre

**Comment by leomurta** [comment]
@braganholo, coloquei em produção. Passe esse problema de formato, juntamente com a análise que o @JoaoFelipe fez para uma nova issue para ser resolvido no futuro.
