### ISSUE TITLE
Padronização de Históricos e Boletins

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#208]
A borda superior e lateral da tabela de trancamentos está preta ao invés de azul tanto no histórico quanto no boletim. Além disso, acho que ficaria melhor se fosse como as tabelas de etapas e prorrogações, sem colunas (essas só aparecem no boletim). Poderia aparecer período e duração tudo junto (nas outras aparece data e nome da etapa ou prorrogação, também tudo junto), tanto no histórico quanto no boletim.

Trancamentos
2015/1 1 Semestre

A fonte usada também não está padronizada. Há mistura de Courier e Helveltica. 

transcript:
:row_colors => ["E5E5FF"],
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right],
                                :border_color => "000080",
                                :align => :left,
                                :padding => [2, 4]
                }

transcript:
#header
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right],
                                :border_color => "000080",
                                :align => :left,
                                :padding => [2, 4]
                }
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right],
                                :border_color => "000080",
                                :align => :center,
                                :padding => [12, 2]
                }
#dados
                    :cell_style => {:font => "Helvetica",
                                    :size => 9,
                                    :inline_format => true,
                                    :border_width => 1,
                                    :borders => [:left, :right],
                                    :border_color => "000080",
                                    :align => :center,
                                    :padding => 2
                    }
#footer
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right],
                                :border_color => "000080",
                                :align => :center,
                                :padding => 2
                }

enrollments_table (que aparece nome do aluno):
                   usa função simple_pdf_table

accomplished/deferrals:
#header
                    :cell_style => {:font => "Courier",
                                    :size => 10,
                                    :inline_format => true,
                                    :border_width => 1,
                                    :align => :center
                    }
#dados
                    :cell_style => {:font => "Courier",
                                    :size => 10,
                                    :inline_format => true,
                                    :border_width => 0,
                                    :align => :left
                    }

enrollment_scholarships:
#header
                  :cell_style => {:font => "Courier",
                                  :size => 10,
                                  :inline_format => true,
                                  :border_width => 1,
                                  :align => :center
                  }
#dados
                  usa função simple_pdf_table

grades_report:
#header
              :cell_style => {:font => "Helvetica",
                              :size => 9,
                              :inline_format => true,
                              :border_width => 1,
                              :borders => [:left, :right, :top, :bottom],
                              :border_color => "000080",
                              :align => :center,
                              :padding => [12, 2]
              }
#dados
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right],
                                :border_color => "000080",
                                :align => :center,
                                :padding => 2
                }
#footer
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right, :bottom, :top],
                                :border_color => "000080",
                                :align => :center,
                                :padding => 2,
                                :font_style => :bold,
                                :text_color => "000000"
                }

thesis_table:
               usa funcao text_table

search_table:
               usa funcao simple_pdf_table

enrollment_holds:
#header
                    :cell_style => {:font => "Courier",
                                    :size => 10,
                                    :inline_format => true,
                                    :border_width => 1,
                                    :align => :center
                    }
#dados
         usa funcao simple_pdf_table           

simple_pdf_table:
#header
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right],
                                :border_color => "000080",
                                :align => :center,
                                :padding => [2, 2]
              }
#dados
                :cell_style => {:font => "Helvetica",
                                :size => 9,
                                :inline_format => true,
                                :border_width => 1,
                                :borders => [:left, :right],
                                :border_color => "000080",
                                :align => :center,
                                :padding => 2
                }

text_table:
não tem estilo. Apenas escreve o conteúdo

**Comment by JoaoFelipe** [comment]
Tentei padronizar o pdf. Extraí funções para cada tipo de tabela: agora é mais fácil editar. (com exceção da tabela de notas, que tem formato próprio e difícil de padronizar)

Transformei trancamentos em lista e coloquei títulos em letra maiúscula.

Não padronizei fontes: a lista de notas usava Courier e as informações do usuário Helvetica.
Acabei deixando Courier para tabelas e títulos; e Helvetica para informações de usuário e listas. 
Se preferir, posso mudar. Acho que helvetica funciona bem para as listas (deixa o mes/ano alinhado)

Pode colocar em homologação

**Comment by leomurta** [comment]
Obrigado João.
Coloquei em homologação. Pode testar, Vanessa.

**Comment by braganholo** [comment]
Ficou ótimo! Obrigada João! Leo, pode colocar em produção.

**Comment by braganholo** [comment]
Acabei detectando um pequeno problema de sobreposição nas tabelas. Deve ser alguma configuração de margem.

**Comment by JoaoFelipe** [comment]
Tentei corrigir ajustando o tamanho da borda. O footer usava pelo menos 96 unidades (não sei se é pixel, point ou outra), mas estava ajustado para 80.

Parece ter resolvido a sobreposição, mas percebi um outro "problema": o título pode ficar separado do resto do conteúdo. Isso me parece trabalhoso de resolver, já que eu teria que calcular quantas linhas de cada tabela poderiam ficar em cada página (ou saber se a tabela cabe na página) e não conheço modo fácil de saber a altura de cada linha/tabela. 
De qualquer forma, acho que não atrapalha muito
![screenshot from 2015-09-16 15 36 12](https://cloud.githubusercontent.com/assets/327789/9914577/de3b5c40-5c88-11e5-8364-6fe568fc770b.png)



Pode colocar em homologação.

**Comment by leomurta** [comment]
Obrigado João.
Já coloquei em homologação. Pode testar, Vanessa.

**Comment by braganholo** [comment]
Pode colocar em produção.

**Comment by leomurta** [comment]
Feito.
