### ISSUE TITLE
Adicionar campo em TURMA

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#209]
Adicionar um campo em TURMA, que diga se aquela turma é para reproveitamento de créditos (às vezes temos que abrir turmas especiais para lançar aproveitamente de créditos). Nesse caso, essa turma não deve aparecer no quadro de horários.

**Comment by leomurta** [comment]
Isso aqui parece já estar implementado tb. Peloq ue vi, saiu no commit https://github.com/gems-uff/sapos/commit/a40cc0e9d3727210892d70d82592338dc8f335c0
Confirma @braganholo ou @JoaoFelipe ? Se sim, vou fechar e vincular com a versão que esse commit saiu.

**Comment by leomurta** [comment]
Acho que esse commit que vc citou só inverte a semântica de aparecer para não aparecer. Mas vou simplesmente fechar essa issue então já que foi resolvido.
