### ISSUE TITLE
Inscrição online no processo seletivo de mestrado e doutorado

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#219]
Regras e documentação exigida: http://www.ic.uff.br/index.php/pt/pos-graduacao/inscricoes 

Formulário de inscrição que usamos no nosso processo seletivo: http://www.ic.uff.br/images/documentos/pos_graduacao/formularios_e_requerimentos/formulario_inscricao.pdf

Essa issue também se relaciona com a issue #157 (carta de recomendação). 

Seria interessante o candidato escolher se quer preencher o formulário de inscrição em português ou inglês (ou outra língua).

**Comment by braganholo** [comment]
Inspiração no Google Docs + opção de adicionar um ou mais idiomas alternativos.

**Comment by JoaoFelipe** [comment]
Para essa issue, pode ser interessante usar a página de "Pendências" planejada em #347. Após a inscrição no processo seletivo, as informações ficariam pendentes na página de alguém (quem? Secretaria? Avaliadores?) e a inscrição de Student poderia ser feita automaticamente através da confirmação no processo seletivo.

Além disso, é necessário ter uma configuração de período de inscrição online. 

Ao fazer uma inscrição, um link seria criado para o envio da carta de recomendação.

**Dúvidas:** Não entendi exatamente qual é a inspiração no Google Docs. Seria Google Forms? As informações cadastradas seriam apenas as do PDF linkado ou teriam outras?

**Comment by braganholo** [comment]
Acho que as inscrições ficariam pendentes na página dos avaliadores. Precisamos criar o conceito de comissão de seleção de mestrado e comissão de seleção de doutorado. E isso muda a cada semestre -- seria legal manter o histórico de quem foi da comissão em qual ano/semestre. 

Quanto à sua dúvida, sim, hoje em dia estamos usando o Google Forms para as inscrições (eu escrevi errado ali no comentário de 2016). As informações são as do PDF. Nós já temos um cadastro de instituições de ensino que não está sendo usando. Seria legal o candidato poder selecionar a instituição em que se formou na graduação -- só teríamos que ver como fazer caso não estivesse cadastrada ainda -- teria um cadastro temporário que depois seria validado pela secretaria? 

Note que o candidato precisa fazer o upload de documentos. Já temos um pull request referente a essa funcionalidade. Seria legal dar uma olhada lá e ver se é possível aproveitar algo.
