### ISSUE TITLE
Tradução de Birth country em Student

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#226]
Na tela de visualização de student, o campo Birth country aparece em inglês. É preciso adicionar a tradução "País de origem" para que apareça corretamente na visualização de aluno. Na tela de edição de aluno esse problema não ocorre porque país e estado estão agrupados na mesma linha com o label "Naturalidade".

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi acrescentada uma tradução para o label birth_country no arquivo config/locales/pt-BR.yml 
Aparentemente a tradução funcionou corretamente na tela de visualização  de student.
