### ISSUE TITLE
Criar papel Suporte com permissão de cadastrar foto de aluno

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#227]
O papel de suporte terá acesso somente à edição de Student.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Aparentemente o papel suporte pode modificar um registro de student, alterando apenas a foto e o email.
Com isso, estou fechando esta issue. Porém percebi dois outros problemas que poderiam ser colocados como issues:
1 - Para poder atualizar uma foto de aluno, antes, é preciso remover a foto antiga e salvar sem foto.
Ao se tentar atualizar um aluno com uma foto já existente, a página fica carregando sem voltar para a listagem.
2 - Se uma foto é atualizada, o url da foto permanece o mesmo. Alguns navegadores não percebem a atualização da foto e usam a antiga (usam o cache) enquanto não se forcar uma atualização na página. O ideal seria que o url da foto tivesse um hash do novo arquivo de imagem, para forçar o navegador a baixar a foto sempre que essa for atualizada.
