### ISSUE TITLE
Erro na busca por alocação de bolsa

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#229]
Ao entrar na tela de busca de Alocação de Bolsa, recebo internal error ao tentar fazer a seguinte consulta: 

Agência = CNPq
Nível = Doutorado
Ativa? = Ativa 

O erro é o seguinte:
Mysql2::Error: Unknown column 'scholarships.id' in 'IN/ALL/ANY subquery'

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Aparentemente esse problema na busca foi resolvido. Foram feitos ajustes nas condições dos seguintes campos de busca: Nível, tipo de bolsa e orientador.
