### ISSUE TITLE
URL de foto

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#231]
Se uma foto é atualizada, o url da foto permanece o mesmo. Alguns navegadores não percebem a atualização da foto e usam a antiga (usam o cache) enquanto não se forcar uma atualização na página. O ideal seria que o url da foto tivesse um hash do novo arquivo de imagem, para forçar o navegador a baixar a foto sempre que essa for atualizada.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi adicionado um hash aos links de foto e imagem, nas telas de aluno e configuração de relatório. Isso aparentemente resolveu o problema porque, quando uma foto é trocada, o navegador mostra a última foto.
