### ISSUE TITLE
Etapa sem data de conclusão

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#232]
Por algum motivo o SAPOS está deixando salvar realização de etapa sem data de conclusão. Isso gera um erro ao tentar vizualisar a matrícula e ao gerar o boletim.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi adicionada uma verificação de presença para data de conclusão no modelo de realização de etapa (accomplishment). Com isso o SAPOS pede o preenchimento do campo data de conclusão.
