### ISSUE TITLE
Erro ao gerar boletim quando aluno tem etapa sem data de conclusão

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#233]
Essa issue está ligada à issue #232. Quando ocorre de uma etapa ter sido salva sem data de conclusão, há erro na geração do boletim e na visualização da matrícula.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Se houver uma etapa sem data de conclusão definida, o boletim ou a página de visualização da matrícula são gerados com uma string ---------/-----.  Uma data definida teria o formato, como por exemplo, de: fevereiro/2017.
