### ISSUE TITLE
Migração do Ruby

### ISSUE THREAD

**Issue by leomurta** [gems-uff/sapos#235]
IMPORTANTE: Criei um ramo "migration" para ser usado na implementação dessa issue, visando manter o isolamento.

Atualmente estamos rodando as seguintes versões:

Ruby: 2.2.0
Rails: 4.2.3

  Pelo que eu li, o Rails 4.2.3 tem como requisito Ruby 1.9.3 ou mais recente (http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions). Sendo assim, pensei em atualizarmos primeiro o Ruby, testarmos e colocarmos em produção para depois continuar a migração para o Rails.

  A versão mais recente do Ruby é 2.4.2. Contudo, a mais recente disponível no RVM é 2.4.1 e no RBenv é 2.4.0. **Minha sugestão é migrarmos então para o Ruby 2.4.1**.

  Dúvida: será que podemos colocar somente 2.4 no Gemfile, já que o último dígito é bugfix? Assim eu poderia atualizar o Ruby sempre que saísse uma nova versão no RVM.

  Criarei uma issue separada para a migração do Rails.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Antes da instalação ou migração desse commit, foram feitas as atualizações do ruby para 2.4.1, e do passenger para 5.1.11.

Se o arquivo mod_passenger.so do passenger estiver em outro local, pode ser necessário atualizar o arquivo httpd.conf do apache com a nova localização.

Para que o comando bundle da conta que instalou o SAPOS funcionasse corretamente com o novo ruby, foi preciso reinstalar a gem bundle, e atualizar a variável de ambiente $PATH no arquivo ~/.bash_profile para apontar para o novo diretório com o executável do bundle,   

Sobre as mudanças feitas no Gemfile:

1 - No arquivo Gemfile, foi modificada a linha do ruby, para ser maior ou igual que 2.4.1, e menor que 2.5. O ruby instalado durante esse teste é o 2.4.1. Tentar instalar deixando a antiga linha do Gemfile (2.2.0)
fez o bundle install sair sem instalar.

2 - O json 1.8.3 não suporta a unificação das classes Fixnum e Bignum (existentes no ruby 2.2) na classe Integer (do ruby 2.4). Com isso ocorrem erros durante o bundle install. A versão seguinte do json (1.8.5) suporta a unificação. No Gemfile foi acrescentada a versão 1.8.5 para a gem json.

3 - A atualização do json fez acontecer um erro na instalação por dependências não resolvidas com relação a gem rdoc. Foi acrescentado no arquivo Gemfile a gem rdoc com a mesma versão já era utilizada no Gemfile.lock (rdoc 4.2.0). Essa versão (4.2.0) porém causou um erro na instalação para produção. A versão rdoc 4.3.0 aparentemente funcionou corretamente. 

4 - O rake db:setup ainda não funcionava (ocorria um erro SystemStackError: stack level too deep). Isso possivelmente acontecia por incompatibilidade do rails 4.2.3 (do arquivo Gemfile.lock) com o ruby 2.4. (em um fórum há uma sugestão de que isso ocorre também por causa de incompatibilidade com a unificação da classe Integer). O rails 4.2.8 é o primeiro a suportar oficialmente o ruby 2.4 (http://weblog.rubyonrails.org/2017/2/21/Rails-4-2-8-has-been-released/) então foi acrescentada a versão 4.2.8 no gem rails do arquivo Gemfile.

5 - A atualização do rails para 4.2.8 (usando bundle update rails) causou a atualização automática de algumas outras gems. Foram feitas tentativas de evitar atualização automática dessas gems com a adição das flags --source e --conservative, porém essas flags fizeram com que o bundle update ficasse processando por horas, tentando resolver as dependências. Devido a isso, foi solicitada a atualização
da gem rails permitindo a atualização de gems. 
Algumas das gems atualizadas automaticamente causarem erros, por exemplo, as gems rake e sprockets. Então se tentou permitir que o mínimo de gems fossem atualizadas automaticamente. Para que as gems mantivessem sua versão antiga, uma lista foi adicionada no arquivo Gemfile, com essas gems e suas versões.
Basicamente se permitiu atualizar as gems que são dependências diretas da gem rails 4.2.8. Além
dessas, se deixou atualizar as gems rails-html-sanitizer (porque a actionview 4.2.8 depende dela) e a gem
arel, porque a antiga causou um erro no rake db:setup por nao trabalhar com o novo inteiro.
