### ISSUE TITLE
Migração do Rails

### ISSUE THREAD

**Issue by leomurta** [gems-uff/sapos#236]
IMPORTANTE: Criei um ramo "migration" para ser usado na implementação dessa issue, visando manter o isolamento.

  Antes de fazer essa issue, deveríamos fazer a issue #235.

  Atualmente estamos rodando a seguinte versão do Rails: 4.2.3. Contudo, a versão mais recente do Rails é a 5.1.4 (https://rubygems.org/gems/rails/versions). Minha sugestão é tentarmos migrar para ela. Contudo, precisamos fazer em dois passos:

- 4.2.3 para 5.0.6: http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0
- 5.0.6 para 5.1.4: http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-0-to-rails-5-1

  Ao término do primeiro passo, podemos fazer todos os testes e depois fazer uma release, para só então começar o segundo passo. Assim teremos um check-point.

  Notei também que algumas libs estão com versões fixadas no Gemfile, como a mysql2 que está com 0.3.15. A menos que seja fundamental termos alguma versão fixada, seria melhor deixarmos o bundler update pegar a lib mais recente possível.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
No primeiro commit, a gem rspec-rails foi atualizada com o comando "bundle update rspec-rails" para que fosse possível atualizar o rake. (a gem rspec-core original utiliza um método descontinuado "last_comment" do rake. Ao se atualizar a gem rspec-rails, a rspec-core é atualizada por ser uma dependência)

O arquivo "config/initializers/assets.rb" foi criado e a gem sass-rails foi atualizada "bundle update sass-rails" para que fosse possível atualizar a gem sprockets

**Comment by leomurta** [comment]
Falta fazer algo nessa issue ou podemos fechar?
