### ISSUE TITLE
Resize de foto de aluno

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#237]
Quando faço upload de uma foto de aluno que tem resolução muito alta, a foto fica grande demais e não pode ser visualizada inteira na tela. Sugiro que a janela de foto tenha um tamanho fixo e que seja feito resize da foto para caber dentro daquele tamanho. Poderia ser o mesmo tamanho que é usado para quando a foto é tirada via webcam.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
As telas com exibição de fotos de aluno obtidas por upload foram modificados para exibir a foto dentro de um retângulo de 400px de largura por 300px de altura, como nas fotos obtidas por webcam
