### ISSUE TITLE
Erro na validação de inscrição em disciplina

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#238]
O SAPOS deveria barrar inscrição duplicada em disciplina (aluno já foi aprovado nessa disciplina e tenta se inscrever novamente). Essa validação existe atualmente na classe Class_Enrollment e funciona quando a inscrição é efetuada na tela de matrícula. No entanto, quando a inscrição duplicada é feita na tela de Turma ou de Inscrição, a validação não está funcionando adequadamente. Acreditamos que seja pelo fato daquela inscrição ainda não estar ligada ao objeto daquela matrícula, e então a condição de validação having("count(course_id) > 1") não pega esse caso. 

A solução seria mudar o método de validação, para excluir essa inscrição (id da inscrição diferente de self) e colocar having("count(course_id) > 0")

**Comment by leomurta** [comment]
@Carlos-Eduardo-Cabral-da-Cunha , tente priorizar essa correção no ramo bugfix para colocarmos em produção o quanto antes. Pensando rápido, acho que algo assim pode funcionar. Só não sei se a sintaxe está 100% correta.

```ruby
other_enrollments = ClassEnrollment.
          joins(:course_class => {:course => :course_type}).
          includes(:course_class => {:course => :course_type}).
          where(CourseType.arel_table[:allow_multiple_classes].eq(false)).
          where(:enrollment_id => self.enrollment_id).
          where(ClassEnrollment.arel_table[:situation].not_eq(DISAPPROVED)).
          where(Course.arel_table[:id].eq( self.course_class.course_id)).
          where.not(:id => self.id).
          group(:enrollment_id).
          having("count(course_id) > 0")
```

**Comment by leomurta** [comment]
Aproveita e troca o nome da variável de other_enrollments para other_class_enrollments, para ficar semanticamente mais correto.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Oi.
Vou dar prioridade a essa correção.

**Comment by braganholo** [comment]
A solução da issue #239 gerou um efeito colateral aqui. Eu consigo colocar uma
reprovação por falta na disciplina de seminários, mas quando tento inscrever o aluno novamente em
Seminários, ele me diz que não posso porque é turma de inscrição
única. Mas isso não deveria estar sendo checado, uma vez que o aluno
reprovou em Seminários, ela é obrigatória e então ele tem que cursar
novamente, mesmo a disciplina sendo de inscrição única.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Pelo que entendi nesse caso, quando uma inscrição em seminários sendo verificada (a self) é a reprovada, a consulta acaba retornando uma outra inscrição em seminários que não está reprovada. Como ela encontra outra inscrição, que não é a self, e que não está reprovada, a validação considera isso como um erro. Se a self tem a situação como reprovada, ela poderia ser desconsiderada durante a busca de outras inscrições. Então foi adicionada uma condição para desconsiderar essas selfs com situação reprovada.
