### ISSUE TITLE
Reprovação por falta em disciplina sem nota

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#239]
Ao tentar registrar reprovação de aluno em Seminários ocorre o seguinte problema: ao marcar o flag de frequência insuficiente, o sistema exige que seja atribuída nota menor ou igual a zero para salvar a alteração. Ao preencher com zero, o sistema impede novamente de salvar, desta vez porque não pode ser atribuída nota a resultado desta disciplina. (Exemplo de disciplina desse tipo: Seminários). 

É preciso alterar a verificação que é feita na reprovação por falta, para testar também se a disciplina é de um tipo que não tem nota. Se for esse o caso, a checagem de nota não deve ser realizada, e o sistema deve forçar que o status seja reprovação.

**Comment by braganholo** [comment]
O erro está nessa validação do modelo class_enrollments.rb

def grade_for_situation
    if course_has_grade
      unless self.grade.blank?
        self.errors.add(:grade, I18n.translate("activerecord.errors.models.class_enrollment.grade_gt_100")) if self.grade > 100
        self.errors.add(:grade, I18n.translate("activerecord.errors.models.class_enrollment.grade_lt_0")) if self.grade < 0
      end
      case self.situation
        when I18n.translate("activerecord.attributes.class_enrollment.situations.registered")
          self.errors.add(:grade, I18n.translate("activerecord.errors.models.class_enrollment.grade_for_situation_registered")) unless self.grade.blank?
        when I18n.translate("activerecord.attributes.class_enrollment.situations.aproved")
		self.errors.add(:grade, I18n.translate("activerecord.errors.models.class_enrollment.grade_for_situation_aproved", :minimum_grade_for_approval=>(CustomVariable.minimum_grade_for_approval.to_f/10.0).to_s.tr('.',','))) if (self.grade.blank? || self.grade < CustomVariable.minimum_grade_for_approval)
        when I18n.translate("activerecord.attributes.class_enrollment.situations.disapproved")
		self.errors.add(:grade, I18n.translate("activerecord.errors.models.class_enrollment.grade_for_situation_disapproved", :minimum_grade_for_approval=>(CustomVariable.minimum_grade_for_approval.to_f/10.0).to_s.tr('.',','))) if (self.grade.blank? || self.grade >= CustomVariable.minimum_grade_for_approval)
      end
    else
      self.errors.add(:grade, I18n.translate("activerecord.errors.models.class_enrollment.grade_filled_for_course_without_score")) unless self.grade.blank?
    end
    self.errors.blank?
  end

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
O javascript foi corrigido para não preencher o campo com uma nota de reprovação por falta quando o tipo de disciplina não tiver nota. A validação do modelo de inscrição em disciplina estava exigindo que, em caso de reprovação por falta, a nota de reprovação por falta estivesse preenchida, mesmo se a disciplina fosse de um tipo que não possui nota. O modelo foi corrigido para não exigir nota nesse caso.

**Comment by braganholo** [comment]
Funcionou mas gerou um efeito colateral. Eu consigo colocar a
reprovação por falta, mas quando tento inscrever o aluno novamente em
seminários, ele me diz que não posso porque é turma de inscrição
única. Mas isso não deveria estar sendo checado, uma vez que o aluno
reprovou em Seminários, ela é obrigatória e então ele tem que cursar
novamente, mesmo a disciplina sendo de inscrição única. Vou registrar
isso lá nessa issue. Vou manter essa issue fechada e reabrir a issue #238.

**Comment by braganholo** [comment]
O bug voltou.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Em um commit que fiz no dia Dec 19, 2017 (link abaixo) algumas mudanças do arquivo  app/models/class_enrollment.rb foram perdidas.  É como se eu tivesse utilizado uma versão antiga desse arquivo (antes dos commits #238 e #239 por exemplo). Eu devo ter cometido algum erro que causou esse efeito. Refiz as modificações.   

Commit onde as mudanças foram desfeitas:   
https://github.com/gems-uff/sapos/commit/c8f85da4a2c4e81fa3c8f79344076837f9e8a8e4
