### ISSUE TITLE
Busca por disciplinas na tela de Matrícula

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#241]
A busca por alunos que cursaram uma determinada disciplina na tela de matrícula está estranha, pois a ordem em que as disciplinas aparecem no combo não é ordem alfabética. Temos disciplinas com o mesmo nome, de currículos diferentes, e isso não está muito explícito. Por exemplo, se escolho buscar por Algoritmos Distribuídos em 2017/1, a busca retorna vazia. Mas, se escolho a segunda ocorrência de Algoritmos Distribuídos (que aparece bem mais abaixo no combo), a busca retorna os resultados corretamente. O ideal seria colocar o código da disciplina junto do nome dela, para ficar mais claro pra quem está usando, ou, melhor ainda, buscar pelo nome, independente do código, colocando apenas nomes únicos na combo box.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Modifiquei o combo box de disciplinas para ficar ordenado e não repetir nomes parecidos (diferentes somente em espaços, caixa e acentos). A busca é feita aceitando nomes parecidos na mesma forma (espaços, caixa e acentos).

**Comment by leomurta** [comment]
Carlos, vc implementou essa issue no ramo migration, mas eu fiquei em dúvida se ela é de fato relacionada com a migração ou se é um bugfix.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Mexendo no SAPOS percebi um problema na correção da issue. Se a tabela de disciplinas estiver vazia, o código causa uma exceção na tela de matrículas.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi feita uma modificação. Aparentemente o erro do id de disciplina inexistente foi corrigido.
