### ISSUE TITLE
Erro ao criar usuário

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#242]
Ao tentar criar usuário, o SAPOS dá um erro:

A NameError occurred in users#create:
  undefined local variable or method `unconfirmed_email' for #<User:0x00007f984170c250>

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
As versões mais novas da gem devise requerem um campo tipo string, chamado de 'unconfirmed_email', na tabela de usuários.  Foi adicionado um arquivo de migração para criar o campo.
