### ISSUE TITLE
Erro ao executar consultas

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#243]
Ao tentar executar uma consulta qualquer na tela de consultas, o SAPOS emite o seguinte erro: 

A NoMethodError occurred in queries#execute:

  undefined method `symbolize_keys' for #<ActionController::Parameters:0x00007f78e23db690>
  app/models/query.rb:16:in `map_params'

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
No rails 4, ele funciona porque a variável que usa o método symbolize_keys é do tipo Hash, com os parâmetros da consulta. No rails 5, a váriavel pode ser do tipo ActionController::Parameters, nem sempre um Hash como no rails 4. Foi utilizado o método to_unsafe_h para obter o Hash com os parâmetros da consulta.

**Comment by braganholo** [comment]
Para as consultas a solução funcionou, mas o mesmo problema ocorre na simulação de envio de notificações. Imagino que o bug lá seja parecido, devido à mensagem de erro enviada pelo SAPOS: 

A ActionController::UnfilteredParameters occurred in notifications#simulate:

  unable to convert unpermitted parameters to hash
  app/models/notification.rb:159:in `merge'

Estou reabrindo essa issue para que o problema seja corrigido.

**Comment by braganholo** [comment]
Para reproduzir o erro, entrar na tela de notificações, escolher uma notificação qualquer e apertar o botão "simular".

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Os problemas nas telas de consultas e notificações estão relacionadas aos parâmetros 'params[:query_params]' e 'params[:notification_params]' que são obtidas nas controllers com o método 'params'. No rails 4, esses parâmetros se comportam como se herdassem métodos da classe Hash, enquanto no rails 5 não. Procurei converter esses parâmetros quando eles são recebidos nas controllers, usando o método 'to_unsafe_h' que retorna um Hash parecido com o do rails 4. No caso das notificações foi preciso adicionar uma permissão no before_action para o parâmetro 'params[:notification_params]', para que ele pudesse ser utilizado nas views sem dar erro de permissão.
