### ISSUE TITLE
Disciplinas duplicadas na tela de turma

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#244]
Na tela de turmas, só devem aparecer disciplinas do currículo vigente. Ao tentar cadastrar uma nova turma, ao clicar no combo para escolher de qual disciplina é uma determinada turma, tudo fica correto. No entanto, basta começar a digitar algum nome de disciplina para a lista mudar e já aparecer nomes duplicados (ou seja, ali o filtro por disciplinas do currículo vigente não está mais sendo respeitado). O mesmo ocorre se, sem digitar nada, muda-se de página na lista de disciplinas.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
O modo como a passagem de parâmetros é feita nas versões mais novas da gem recordselect mudou. Antes ele usava uma hash 'params' do modo como ele era passado para o controller da classe. Agora ele considera apenas parâmetros extras que são passados pelo método  'permit_rs_browse_params', que deve ser definido no helper da classe.

**Comment by braganholo** [comment]
Não seria bom criar uma nova issue para verificar se isso não afeta outras telas então?

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Sim. É possível fazer uma busca pelos campos recordselect existentes e
ativar um erro por exceção para facilitar a perceber a falta de algum
parâmetro.

Em 22 de fev de 2018 7:41 PM, "Vanessa Braganholo" <notifications@github.com>
escreveu:

**Comment by braganholo** [comment]
Criei a issue #245 para isso.
