### ISSUE TITLE
Parâmetros em record select

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#245]
O modo como a passagem de parâmetros é feita nas versões mais novas da gem recordselect mudou. Antes ele usava uma hash 'params' do modo como ele era passado para o controller da classe. Agora ele considera apenas parâmetros extras que são passados pelo método 'permit_rs_browse_params', que deve ser definido no helper da classe.

É preciso fazer uma busca pelos campos recordselect existentes no sistema para verificar se são afetados por essa mudança. Estou cadastrando essa issue como bug. 

(Ver histórico na issue #244)

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Fiz uma busca pelos campos recordselect das telas e testei com uma exceção para erro na falta de parâmetros habilitada. Acrescentei a permissão de parâmetros para esses campos recordselect e depois desabilitei a exceção novamente. Não encontrei outros campos que usassem filtros diferentes. Apenas o controller courses parece utilizar um parâmetro a mais em seu recordselect, que é  o :available.

**Comment by leomurta** [comment]
Coloquei em homologação. Vc pode testar, @braganholo ?

**Comment by braganholo** [comment]
Está ok. Pode colocar em produção.
