### ISSUE TITLE
Turmas de algumas disciplinas não aparecem no record select

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#246]
Está ocorrendo um erro estranho nas telas de Matrícula e de Inscrições. Ao tentar inscrever um aluno na turma de Análise e Síntese de Algoritmos 2018/1 essa turma não aparece no Record Select. Outras um pouco mais antigas também não aparecem. Não fazemos ideia do motivo. A princípio só notamos o erro com essa disciplina, mas pode ser que esteja acontecendo com outras. 

Ao investigar esse bug notamos também dois problemas que precisam ser resolvidos: 

1) Aparecem turmas repetidas no Record Select. Investigando um pouco mais notamos que na verdade não são turmas repetidas -- é que foram oferecidas duas turmas daquela disciplina no mesmo ano/semestre. Isso ocorre por exemplo com Análise e Síntese de Algoritmos em 2012/1. Mas, para diferenciar essas turmas, elas possuem nomes diferentes. No record select é colocado apenas o nome da turma seguido do ano semestre, e isso dá a impressão da repetição. Isso causa um efeito colateral indesejado, pois na hora de fazer a matrícula não se pode ter certeza de qual a turma correta para colocar um determinado aluno entre as duas opções disponíveis. Quando a disciplina é de Tópicos, o nome da turma aparece entre parênteses no Record Select. A sugestão então para evitar esse problema da sensação de duplicidade é que sempre que o nome da turma for diferente do nome da disciplina, o nome da turma deve ser colocado entre parênteses no Record Select. 

2) As turmas de uma mesma disciplina no Record Select aparecem em ordem aleatória, o que dificulta o processo de inscrição. Elas deveriam aparecer em ordem decrescente de ano/semestre. 

Notar que tudo isso deve ser feito tanto na tela de matrícula quanto na tela de inscrições.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Esse bug parece estar relacionado a um problema de paginação. A consulta SQL traria o número e conjunto correto de registros. Porém, ao se paginar, a SQL repetiria alguns registros entre as páginas de resultados, e deixaria de exibir outros. 

Por exemplo, isso acontece na tela de turmas da homologação. Quando se busca pelo nome "Análise e Síntese de Algoritmos", as páginas de resultados não exibem um registro de 2018, e alguns registros se repetem nas páginas 1 e 2. Ao se restringir mais o filtro de busca, colocando além do nome, o ano 2018,
o registro de 2018 passa a ser exibido.

Essa página fala um pouco sobre o problema da paginação:
https://github.com/mislav/will_paginate/issues/420

Aparentemente seria possível corrigir o problema de paginação ao se acrescentar alguma chave única na ordenação do SQL, como o id por exemplo.   
 
Acrescentei uma ordem por id na página de busca de turmas, para ver se os registros passam a ser exibidos corretamente nas páginas 1 e 2. Não pude testar porque ainda não consegui reproduzir o erro de paginação no meu ambiente. Acredito que isso deva ser visível na página de homologação. 

Acrescentei uma view para a record_select de turmas exibir o nome da turma caso os nomes da turma e disciplina sejam diferentes.  Acrescentei ordenação por ano, semestre e id no record_select de turmas, para tentar resolver o problema de paginação.
