### ISSUE TITLE
Log sem usuário

### ISSUE THREAD

**Issue by leomurta** [gems-uff/sapos#248]
Desde 12/01/2018 os logs (menu Configurações/Log) não indicam o usuário que fez a mudança. Estou suspeitando, pela análise das datas, que esse bug entrou em uma das duas releases abaixo:

https://github.com/gems-uff/sapos/releases/tag/4.4.5 (suspeito mais dessa)
https://github.com/gems-uff/sapos/releases/tag/4.4.6

Tendo em vista que isso é um problema de segurança, acho que tem alta prioridade.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
O problema parece ter sido causado por uma diferença na configuração da gem paper_trail quando ela foi atualizada. A versão que está em uso no momento, a 8.0.1, requer que se insira uma linha no arquivo app/controllers/application_controller.rb, sem a qual não inclui o usuário que causou o evento no registro de logs.  Realmente a versão 4.4.5  do SAPOS já estava com a versão 8.0.1 da paper_trail, equanto o SAPOS 4.4.4 estava com o paper_trail 3.0.7, que não requer essa linha.
