### ISSUE TITLE
Omitir turmas de aproveitamento no Quadro de Horários

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#249]
Algumas turmas são abertas apenas para aproveitamento de créditos (o aluno cursou antes como avulso e quer aproveitar os créditos num semestre em que não está sendo oferecida uma turma daquela disciplina). Nesse caso, a turma existe apenas para possibilitar esse aproveitamento. Ela portanto não deveria aparecer no Quadro de Horários. 

Atualmente não há como separar uma turma de aproveitamento de uma turma regular. Para tratar esse problema, sugiro adicionarmos um atributo em turma que diga se aquela turma é aproveitamento ou não. Turmas marcadas como aproveitamento não devem aparecer quando se gera o quadro de horários.

**Comment by leomurta** [comment]
Acho que essa issue é duplicada da issue https://github.com/gems-uff/sapos/issues/209. Além disso, acho que já foi implementado, conforme comentei na outra issue. Confirmam @braganholo e @JoaoFelipe ?

**Comment by braganholo** [comment]
Sim, a issue é duplicada, e ambas já foram resolvidas.
