### ISSUE TITLE
Corrigir teste de spec do modelo Dismissal

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#268]
Ocorrem erros durante o teste de spec quando executado o comando:
rspec spec/models/dismissal_spec.rb 
Com a seguinte falha "A validação falhou: Número da Bolsa não pode ser alocado a esta Matrícula porque eles são de níveis diferentes"

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
A FactoryGirl da classe ScholarshipDuration estava criando essa classe, com atributos enrollment e scholarship_duration com níveis diferentes. O nível desses atributos devem ser o mesmo para que a ScholarshipDuration esteja correta. Foi feita uma modificação para que os níveis sejam iguais.

**Comment by braganholo** [comment]
Sei que a issue é relacionada a teste, mas parece que há um efeito colateral em desligamento. Estou tentando desligar um bolsista para testar, então deveria dar uma mensagem de erro dizendo que ele não pode ser desligado pq tem bolsa ativa. No entanto, nenhuma mensagem de erro aparece, mas o desligamento não é realizado. Como não dá erro, a impressão que dá é que o desligamento foi feito, mas na realidade não foi.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi necessário incluir uma validação do tipo 'validates_associated' para o modelo desligamento no modelo matrícula, para que a validade do desligamento fosse verificada antes da atualização da matrícula. A modificação fez com que um matcher do rspec deixasse de funcionar corretamente para o teste do desligamento. Foi feita uma mudança para corrigir o matcher.
