### ISSUE TITLE
Alerta de segurança para vulnerabilidade da gem devise

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#290]
A página github do sapos alertou sobre uma vulnerabilidade de segurança da gem devise menor que a versão 4.6.0 (A instalada no momento dessa issue é a 4.3.0). Ele sugeriu a inclusão da nova versão no arquivo Gemfile.

Detalhes sobre a vulnerabilidade:
https://github.com/plataformatec/devise/issues/4981

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
O arquivo Gemfile foi atualizado para a gem devise. O comando bundle install atualizou automaticamente algumas gems da qual o devise depende.

**Comment by braganholo** [comment]
Testei e obtive um erro. Consegui fazer o login sem problemas. Fui na tela de usuários, e tentei trocar o papel de um determinado usuário. O sistema lançou erro dizendo: 

Mysql2::Error: Column 'encrypted_password' cannot be null: UPDATE `users` SET `role_id` = 4, `encrypted_password` = NULL, `updated_at` = '2019-03-22 15:41:14' WHERE `users`.`id` = 74

Note que não deveríamos exigir a senha para trocar o papel do usuário, uma vez que não sabemos as senhas dos usuários (e nem deveríamos saber).

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
A gem devise, da versão 4.5.0 para a 4.6.0, teve uma modificação que causou problemas de compatibilidade em algumas aplicações. Com isso os desenvolvedores do devise resolveram reverter a modificação na versão 4.6.2.

Alguns detalhes sobre a modificação da devise pode ser visto no link:
https://github.com/plataformatec/devise/issues/5033#issuecomment-476386275
