### ISSUE TITLE
Checagem de alocação de bolsa causa erro mesmo para alocação de bolsa já encerrada

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#293]
Estamos com um erro no SAPOS causado por uma validação que está sendo feita mesmo em bolsas já encerradas (e isso não deveria estar sendo feito). A situação é seguinte: 

Um aluno A recebe uma bolsa B1 com data limite de alocação em Julho de 2019. Esse mesmo aluno tem a alocação dessa bolsa encerrada em Fevereiro de 2017, e em Março de 2017 ele passa a receber a bolsa B2 de outra agência com limite de alocação até Julho de 2019. 

Nesse meio tempo, a validade da bolsa B1 (data de fim da bolsa, e não da alocação) é ajustada para Março de 2017 (ou seja, essa bolsa sai do sistema e não pode mais ser concedida a nenhum aluno). Apesar da alocação da bolsa B1 ao aluno A continuar válida (a alocação da bolsa foi encerrada em fevereiro de 2017 e a data de fim da bolsa é março de 2017), o SAPOS reclama que a data limite de alocação da bolsa B1 para o aluno A é inválida (pois agora essa data limite -- Julho de 2019  -- é realmente maior que a data de fim da bolsa -- março de 2017). No entanto, a alocação da bolsa está encerrada ANTES de março de 2017, e portanto não deveria haver erro gerado pelo SAPOS.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Quando se está editando uma bolsa que tenha pelo menos uma alocação, na tela de bolsas, acontecem erros em algumas situações. Se as datas de início e ou fim da bolsa forem alterados de forna a ficarem inválidas em relação as datas de alocação, acontece um erro interno. O mesmo acontece se as datas de alocação de bolsa forem editadas. Então fiz algumas modificações no spec de bolsas para testar esses casos, e fiz mudanças para corrigir eles.
