### ISSUE TITLE
Relatório de prorrogações concedidas

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#303]
Deveria ser possível emitir um relatório com as prorrogações concedidas em um determinado mês, e o SAPOS não tem essa funcionalidade.

**Comment by leomurta** [comment]
@braganholo , isso aqui não poderia ser uma consulta?

**Comment by braganholo** [comment]
Sim, poderia.

**Comment by leomurta** [comment]
Vou fechar a issue então.
