### ISSUE TITLE
Permitir troca de papel de usuário professor

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#310]
Usuários que são do tipo Coordenador ou Administrador também deveriam poder ser vinculados a um professor. Isso facilitaria os casos de troca de coordenação, por exemplo. Da forma como está hoje, quando um professor X é coordenador, ele não tem professor vinculado. Quando ele deixa de ser coordenador e volta a ser professor, seria necessário fazer a vinculação com professor. Mais ainda, o novo coordenador (que antes era professor) tem que ser desvinculado do professor, pois o SAPOS atualmente não aceita coordenador vinculado a professor. 

Permitir essa vinculação faria com que essas trocas fossem mais fáceis no futuro.

**Comment by leomurta** [comment]
Vou fechar essa issue para concentrar tudo na #401.
