### ISSUE TITLE
Alterações na tela de lançamento de notas

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#311]
Nossos dois beta testers reclamaram do tamanho do campo de matrícula na tela de lançamento de notas. Disseram que aparece apenas o primeiro nome do aluno e que isso pode causar confusão quando tivermos alunos com o mesmo primeiro nome. É necessário: 

1) aumentar um pouco aquele campo;
2) retirar o ícone verde que aparece nesse campo (acho que já investigamos isso no passado mas não me lembro qual foi a conclusão).

**Comment by leomurta** [comment]
Precisamos priorizar isso. Os professores tiveram dificuldade em lançar as notas nesse semestre por conta desse problema.
