### ISSUE TITLE
Disciplinas duplicadas na tela de Criação de Turmas

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#313]
O combo box da tela de criação de turmas apresenta disciplinas duplicadas, incluindo disciplinas de currículos antigos. O correto é que essa combo só apresente as disciplinas do currículo vigente.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi adicionada uma condição na função que filtra o resultado para record_select gerado para mostrar disciplinas.  Se uma ação _browse_ vem do _record_select_ da página de turmas, a função filtra para que sejam buscadas apenas disciplinas do currículo vigente
