### ISSUE TITLE
Valor NULL em prazo máximo de Tipo de Etapa

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#314]
Recentemente tivemos um bug em produção que foi causado porque o SAPOS permitiu cadastrar um Tipo de Etapa com valor NULL (vazio) para prazo máximo em Meses. Como o SAPOS soma esses valores de prazo máximo para calcular quando um determinado aluno tem que cumprir uma determinada etapa, e ele não sabe somar NULL, dá um erro. É preciso adicionar um teste antes de salvar o tipo de etapa, não deixando nenhum dos valores de prazo máximo (dias, meses e períodos) ser informado como vazio. Note que o valor pode ser zero, mas não pode ser vazio.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foram adicionados testes rspec e validações para o modelo PhaseDuration que verificam se os campos de prazo máximo de períodos, meses e dias são números inteiros.
