### ISSUE TITLE
Permitir envio de notificação com boletim anexado

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#333]
Foi solicitada uma notificação que pudesse enviar para cada aluno regular ativo seu boletim como anexo. Para que isso seja possível, é preciso fazer algumas mudanças no código.

**Comment by Wilker** [comment]
Feature muito bem vinda!

**Comment by anselmobattisti** [comment]
Muito obrigado! 

Excelente iniciativa
