### ISSUE TITLE
Permitir que professores possam lançar notas em datas diferentes das configuradas do semestre atual

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#339]
No momento os professores podem lançar nota apenas para turmas que estejam no semestre atual definido no sistema. Ocorreu um caso em que está sendo necessário permitir que professores possam lançar notas para suas turmas fora do semestre atual definido.

**Comment by leomurta** [comment]
As opções passam a ser as seguintes:
- no: lançamento de notas desabilitado
- yes: lançamento de notas habilitado para o semestre corrente
- yes_all_semesters: lançamento de notas habilitado para todos os semestres
