### ISSUE TITLE
Página de aluno

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#353]
Inicialmente pensei na issue #346 como sendo acesso + página de aluno, mas pelos comentários da issue #347 relacionados a como deve ser feita a inscrição para alunos com várias matrículas, acho melhor quebrar a issue. A #346 ficaria sendo só relacionada a dar acesso a alunos, enquanto esta issue serve para discutir como seria a página do aluno do aluno.

A página de aluno poderia dar acesso a cada matricula de forma independente. Algo assim:
![image](https://user-images.githubusercontent.com/327789/127216463-c49434bd-884f-4a8d-a762-9fb88f7e91a2.png)

Fiz rapidamente editando o HTML do SAPOS. Com estilo certo daria para fazer algo melhor, colocando as ações como uma barra no topo, por exemplo. Além disso, vou criar uma issue separada para a parte de mostrar etapas/prorrogações, para essa parte não ficar muito complicada.

Alguma validação teria que ser feita para evitar que algumas ações aparecessem para matriculas antigas. Por exemplo, evitar que o aluno faça inscrição na matricula de mestrado se já possuir uma matricula de doutorado válida.

Além disso, é necessário pensar em como abrir a matrícula certa por padrão: é sempre a mais recente?

**Comment by braganholo** [comment]
Achei a ideia bem legal. A matrícula padrão é sempre a mais recente sim. Para evitar ações de inscrição em matrículas passadas, basta checar se já há um registro de desligamento para aquela matrícula -- nesse caso ela teria que ficar read only nessa sua interface.

**Comment by braganholo** [comment]
Um comentário importante: na sua tela de exemplo aparece a matrícula de avulso. Só lembrando que ali devem aparecer apenas as matrículas para as quais poderia existir um usuário (conforme configurado). Se avulso for marcado como não pode ter usuário associal, então as matrículas de avulso não devem aparecer nessa tela, mesmo que aquele aluno específico tenha acesso ao sistema por ter matrículas de outro tipo (mestrado e doutorado no seu exemplo). Minha preocupação aqui é em manter a consistência da interface para garantir que ela não vai mostrar nada para o aluno que não deveria ser mostrado.

**Comment by leomurta** [comment]
Achei super legal, @JoaoFelipe . Acho que seria legal ter uma landing page para os outros papeis também (professor, coordenador, secretaria). Mas isso pode ser outra issue, que será mais fácil quando essa ficar pronta.

**Comment by anselmobattisti** [comment]
**Sugestão de feature**

Permitir que o aluno possa gerar o PDF com o histórico escolar, tanto do mestrado como do doutorado.

**Comment by leomurta** [comment]
Pode ser legal dar uma olhada na visualização atual de matrícula. Lá já tem várias coisas interessantes que poderiam aparecer aqui.

**Comment by JoaoFelipe** [comment]
Coloquei os códigos das matrículas na lateral, com a matrícula mais recente sendo selecionada automaticamente:

![image](https://user-images.githubusercontent.com/327789/132137391-4679aeec-b9b2-4e4a-9deb-c3916131446f.png)

As informações da página de aluno estão na issue #354
