### ISSUE TITLE
Exibir etapas e prorrogações na página de aluno

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#354]
Para não deixar a página de aluno (#353) dependente disso, estou separando a issue. Não cheguei a pensar a fundo no que seria necessário fazer para esta issue. A princípio penso que seria necessário ter uma forma de associar tipos de etapas (phases) e tipos de prorrogação (deferral_types) ao par [nível, tipo de matricula] e usar isso para exibir na página de matrículas que se encaixem nessa condição, mostrando se foi concluida ou não.

**Comment by braganholo** [comment]
Já temos isso no SAPOS, João. Cada etapa está associada com um ou mais níveis (mestrado/doutorado, etc). O que não temos, por exemplo, é o número de créditos que o aluno precisa cursar, e nem quantas disciplinas obrigatórias, obrigatórias de área, optativas, etc. Para isso, acho que precisaríamos criar o conceito de currículo no SAPOS. Mas isso por si só já seria uma outra funcionalidade mais complexa. Podemos cadastrar isso como issue e deixar no backlog se vcs acharem interessante.

**Comment by leomurta** [comment]
Talvez pudéssemos configurar o básico como variável ou mesmo numa entidade "currículo" inicial só para possibilitar mostrar pendências. Por exemplo, se indicarmos que são necessárias duas básicas e o aluno só fez uma, isso poderia aparecer como uma pendência.

**Comment by JoaoFelipe** [comment]
Coloquei quase todas as informações disponíveis da visualização de Matrícula na página de matrícula (incluindo prorrogações e etapas):
![image](https://user-images.githubusercontent.com/327789/132137259-4e4a17a6-5c16-4372-96d7-2043a0662af2.png)

Removi os campos de observação (já que imaginei que pudessem deixar escapar informações internas) e os campos de matrícula de professor em orientações.

Como reusei as tabelas da visualização de matrícula, também fiz alterações lá, então vale verificar também. Uma das alterações foi na tabela de etapas: antes tinha uma tabela de realização de etapas com observações e outra tabela de etapas com com prazos. Juntei as duas tabelas.

**Comment by leomurta** [comment]
Em "Aluno" / "Matrícula", ao clicar no olhinho, está aparecendo a data com dia. Basta aparecer como no screnshoot acima, com somente mês (por extenso) e ano.
