### ISSUE TITLE
Validação de Senha de usuário não está funcionando

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#355]
Atualmente é possível definir uma senha diferente da confirmação e o SAPOS aceita (tanto na interface quanto no form de resetar senha).

Aparentemente, o devise não está configurado como `:validatable`. Vou configurar e ver se tem alguma outra implicação. Se tiver, userei `validates_confirmation_of`

**Comment by JoaoFelipe** [comment]
Parece que o `:validatable` tem 3 confirmações

- Presença de email (já temos separado)
- Presença de senha com número mínimo de caracteres
- Confirmação de senha

A parte de presença de senha deu problema usando o active scaffold: não consegui editar usuário sem alterar senha. Então adicionei só a confirmação de senha com o `validades_confirmation_of`. Podem homologar o branch bugfixes

**Comment by braganholo** [comment]
A validação funcionou, mas a mensagem de erro está estranha:

"Digite a senha novamente não está igual". Poderia ser algo como "As senhas digitadas não são iguais. Por favor, digite-as novamente."

**Comment by braganholo** [comment]
Além disso, após trocar a senha pela interface, não consigo mais fazer nada no sistema. Tenho que fazer logout e login novamente. Como será que poderíamos resolver isso? Talvez colocar uma mensagem pedindo ao usuário para fazer login novamente?

**Comment by leomurta** [comment]
Não dá para forçar o logout automaticamente e voltar para a tela de login?

  Leo

**Comment by JoaoFelipe** [comment]
No rails, o nome do atributo ("Digite a senha novamente") precisa aparecer no início. Tem como tirar essa limitação com uma gem (https://github.com/nanamkim/custom-err-msg), mas ela não recebe atualização há 6 anos e só é instalável por git. Será que vale a pena?

Uma alternativa é mudar o nome do campo para "Confirmação de senha". Com isso a mensagem fica "Confirmação de senha não está igual". Ou poderia ser "Confirmação de senha não está igual à senha. Por favor, digite-as novamente.". Que tal?

Vou ver esse problema da troca de senha pela interface agora.

**Comment by JoaoFelipe** [comment]
Parece que o problema da alteração de senha era justamente que o Devise faz o logout automático ao trocar a senha, mas o active scaffold só atualiza o formulário parcialmente, então tudo deixa de funcionar ao invés de ir para a tela inicial. Corrigi mantendo o usuário logado (apenas na sessão atual) após a troca de senha. Se o usuário estiver logado em outro lugar, ainda deve desconectar.

Também alterei o atributo/mensagem para "Confirmação de senha não está igual à Senha". Podem testar outra vez

**Comment by leomurta** [comment]
Obrigado @JoaoFelipe . @braganholo , coloquei em homologação. Você poderia testar novamente?

**Comment by braganholo** [comment]
Testei e está ok. Pode colocar em produção.
