### ISSUE TITLE
Configuração de Template de Email

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#358]
Fazendo a issue #347, percebi que diversos novos templates de email precisam ser definidos e configurados para ela:

- Email para notificar aluno que pedido de inscrição foi feito
- Email para notificar orientador que pedido de inscrição foi feito
- Email para notificar aluno que orientador deu feedback/validou
- Email para notificar aluno que inscrição foi efetivada

Para a issue #346 o template de email foi definido na variável CustomVariable.account_email. Posso definir esses templates novos como CustomVariable também, mas a interface de edição não é tão boa (já que variáveis são genéricas) e talvez fiquem muitas variáveis de email dificultando a configuração:

![image](https://user-images.githubusercontent.com/327789/131223256-cd840c7c-6ca5-464e-b378-24ef80140085.png)

Ao invés disso, talvez seja melhor definir uma configuração de template separada baseadas na configuração de notificações:

![image](https://user-images.githubusercontent.com/327789/131223289-fd9850fb-d84a-4f47-aca0-d615c7831934.png)

Essa configuração de template de email poderia servir tanto para as notificações hardcoded que estou fazendo agora (#346 e #347) quanto para as configurações do devise. O template também poderia ser usado nas notificações configuráveis para diminuir redundância no controle de redirect_email. 

O que acham? Vale a pena investir tempo nisso ou é melhor usar tudo como CustomVariable mesmo por enquanto?

**Comment by leomurta** [comment]
Eu achei legal ter os templates de e-mail dessa forma que você falou. Fica mais fácil de customizarmos depois, se for necessário.

**Comment by braganholo** [comment]
Eu tb gostei da ideia!

**Comment by JoaoFelipe** [comment]
Feito. Na tela de configurações é possível adicionar templates para emails hardcoded do SAPOS:

![image](https://user-images.githubusercontent.com/327789/131265593-111541b8-74e4-4b61-b196-d8c8cc1fd9e7.png)

A parte de usar esse modelo de template para notificações ficou para #360.

Durante a homologação é bom dar uma passada por todas as ações (não é necessário criar os templates) que geram esses emails, já que a forma de referenciar variaveis mudou em relação à forma hardcoded de antes.

As ações são:
- Criar etapa: accomplishments:email_to_student, accomplishments:email_to_advisor
- Criar orientação: advisements:email_to_advisor
- Editar inscrição: class_enrollments:email_to_professor, class_enrollments:email_to_student, class_enrollments:email_to_advisor
- Editar matrícula: class_enrollments:email_to_professor
- Editar turma: course_classes:email_to_professor
- Criar prorrogação: deferrals:email_to_student, deferrals:email_to_advisor
- Criar usuário: devise:confirmation_instructions
- Criar matrícula para estudante: devise:invitation_instructions
- Pedir para resetar senha: devise:reset_password_instructions
- Pedir para desbloquear conta: devise:unlock_instructions (apesar de ter a opção na tela inicial, não tenho certeza se dá para usar sem bloquear conta. E não dá para bloquear conta atualmente)

Acho que as os emails de trocar senha (devise:password_change) e trocar email (devise:email_changed) não são usados atualmente.

**Comment by leomurta** [comment]
Obrigado @JoaoFelipe . Já lancei a feature. Por favor, pegue a info que vc detalhou aqui e coloque no manual. Obrigado.
