### ISSUE TITLE
Data de consulta para envio de notificações

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#364]
Verificar melhor o valor padrão que aparece na data de consulta na tela do envio de notificações. Ao deixar o campo em branco, ele é preenchido com um valor que não é a data atual

**Comment by leomurta** [comment]
Carlos, estou tendo dificuldade de programar uma notificação manual. Ao pedir para ela ser simulada, nada acontece. Será que é por conta desse bug? Essa notificação não tem a variável data_consulta.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Leonardo, verifiquei que para o caso da simulação da notificação não funcionar quando não há parâmetro, seria um outro bug. Vou criar uma issue diferente para o bug da simulação.
