### ISSUE TITLE
Permitir que uma inscrição em disciplina não conte no cálculo do CR

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#366]
É desejável que algumas inscrições de disciplinas (por exemplo, uma inscrição em disciplinas aproveitadas de outras instituições) não tenham nota contabilizada no CR do aluno. É possível acrescentar da tela de inscrição de disciplina um checkbox para que a nota da inscrição não entre no cálculo da CR

**Comment by leomurta** [comment]
De acordo com o Roberto, da PROPPI, "Normalmente os PPGs sinalizam a disciplina com * e informam no campo de Observações "Disciplina cursada no PPG xxxxxxxxxxxx e aproveitada xxxxxxx."
Os créditos e a carga horária contam na carga horária final."

Sendo assim, acho que poderíamos ter na tela de inscrição em disciplinas, além da checkbox para informar se deve ou não contabilizar no CR ("Não contabilizar nota no CR", um campo de justificativa para caso essa checkbox seja marcada. Aí colocaríamos o * no espaço para nota no histórico e colocaríamos a justificativa digitada nas observações, conforme indicado pelo Roberto.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foram adicionados na tela de inscrições em disciplinas dois campos: um checkbox que permite escoher se a nota da disciplina é considerada no cálculo do CR, e um campo de justificativa. Esses campos refletem nos relatórios pdf de histórico e boletim

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi feita uma mudança no label do campo do checkbox criado na tela de inscrição de disciplinas e nos arquivos pdf de histórico / boletim, no cabeçalho da caixa das disciplinas que não contam nota, sendo removido a expressão _no CR_
