### ISSUE TITLE
Login por CPF

### ISSUE THREAD

**Issue by cipherbreaker** [gems-uff/sapos#369]
Prezados,

recebi ainda agora o email sobre a criação dos usuários no SAPOS. Percebi que o login é feito através do email cadastrado na lista da pós, e não pelo email institucional (iduff). Considerando que o CPF é uma informação existente devido os dados cadastrais e disponível para consulta, o que acham de realizar o login através do mesmo?

Isso se justifica ainda pela questão "padrão UFF" existente em outros sistemas e facilidade de acesso. Ou seja, não ter que lembrar qual foi o email cadastrado na lista da pós, ou ter que usar CPF num sistema e email no outro.

Abraços!

**Comment by JoaoFelipe** [comment]
Me parece uma boa sugestão. Como o sistema já usa email para acesso de professores, talvez o melhor seja fazer [algo que permita email ou cpf](https://stackoverflow.com/questions/2997179/ror-devise-sign-in-with-username-or-email)

**Comment by braganholo** [comment]
Realmente é interessante, mas não é o padrão do SAPOS e nós temos várias
outras demandas mais prioritárias. Eu marcaria como algo pro futuro, quando
e se sobrar tempo.

>

**Comment by leomurta** [comment]
Será que todo usuário tem CPF? Nós temos alunos e professores que não são brasileiros.

Mas concordo que a prioridade disso é baixa, até porque, com a funcionalidade de troca de e-mail, os alunos poderão cadastrar o e-mail do iduff.

**Comment by braganholo** [comment]
Pelo que me lembro, a permissão de permanência no Brasil exige o CPF para
os estrangeiros. Mas, de todo modo, vamos manter baixa prioridade aqui.

>

**Comment by JoaoFelipe** [comment]
Implementei. O login usa a seguinte ordem de prioridade:
- Email
- CPF de Professor
- CPF de Aluno
Se algum professor tiver conta de aluno com email diferente, o login vai para a conta de professor.


\* Mensagem de commit errada. Era para ser "allow login by CPF".
