### ISSUE TITLE
Conceito de currículo

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#371]
Como discutido na #354, se quisermos indicar para alunos quantas disciplinas faltam de cada tipo (obrigatórias de área, optativas, etc), é necessário definir um conceito de currículo.

Não sei se devemos colocar prioridade nisso agora, mas criei a issue para discussão não se perder depois de fechar a outra issue.

**Comment by nataliacfUFF** [comment]
Acho legal criar esse conceito do currículo...Facilitaria a atualização das
regras e a verificação das pendências. Acho que é uma coisa importante e
que poderia ganhar uma prioridade.

Abs,

Natalia
*Natalia Castro Fernandes*

*Coordenadora do Programa de Pós-Graduação em Engenharia Elétrica e de
Telecomunicações (PPGEET)Escola de Engenharia - UFF*


Em dom., 5 de set. de 2021 às 15:15, João Felipe N. Pimentel <
***@***.***> escreveu:

**Comment by JoaoFelipe** [comment]
Quais pendências o currículo deve ter?

**Comment by nataliacfUFF** [comment]
Oi João,

O número de matérias obrigatórias, o conjunto de matérias obrigatórias, e o
número total de matérias....Pode existir também obrigações como fazer a
disciplina de seminários, ou algo desse tipo que pode variar de curso para
curso. Seria interessante que os alunos recebessem esse feedback do que
falta, pois o que falta e o tempo que falta são as dúvidas recorrentes que
mais recebemos na secretaria. E tudo isso embola quando tem reforma
curricular, pois ficam dois grupos de alunos com regras diferentes ao mesmo
tempo.

Abs,

Natalia
*Natalia Castro Fernandes*

*Coordenadora do Programa de Pós-Graduação em Engenharia Elétrica e de
Telecomunicações (PPGEET)Escola de Engenharia - UFF*


Em ter., 7 de set. de 2021 às 17:54, João Felipe N. Pimentel <
***@***.***> escreveu:

**Comment by leomurta** [comment]
Essa issue é duplicada da issue https://github.com/gems-uff/sapos/issues/175. Vou fechar essa para concentrarmos lá.
