### ISSUE TITLE
Permitir que admin e coordenador estejam associados a Professor

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#377]
Atualmente, coisas relacionadas a orientações existem apenas para usuários com cargo Professor e apenas professor pode estar associado à entidade Professor

Mas admins e coordenadores também podem ser professores e ter orientandos.

Uma possibilidade é ter contas diferentes a mesma pessoa com tipos de usuários diferentes, mas o ideal seria que uma mesma conta funcionasse das duas formas.

Para tratar essa issue da maneira certa, além de permitir a associação, é necessário buscar todo lugar que verifica se o usuário é professor e usar o cancan para verificar no lugar. Exemplos de verificações:
- `role_id == Role::ROLE_PROFESSOR`
- `user.professor.blank?`
- `user.professor.nil?`
- `user.professor.present?`

**Comment by JoaoFelipe** [comment]
Parece que essa issue é a mesma que a #310

**Comment by leomurta** [comment]
Vou fechar essa issue para concentrar tudo na #401.
