### ISSUE TITLE
Permitir ocultar etapas antigas para as matrículas recentes

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#387]
Etapas antigas, que não são mais necessárias para matrículas recentes, são exibidas no SAPOS para essas matrículas. Excluir as etapas antigas poderia ser uma solução, mas se perderia elas do histórico das matrículas antigas. Uma possível melhor solução seria incluir um _checkbox_ que permitisse desativar uma etapa. Isso permitiria para ocultar etapas antigas sem excluí-las do SAPOS.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Foi adicionado um campo _active_ no modelo de etapas. Se ele estiver com o valor falso, a etapa deixa de ser exibida na tela de uma matrícula e nas listagens de busca de matrícula, a menos que a etapa tenha sido concluída.

**Comment by leomurta** [comment]
@Carlos-Eduardo-Cabral-da-Cunha , vou reabrir essa issue. Ao usar o Sapos agora, notei que continua aparecendo na combobox da página de edição de uma matrícula as etapas que não estão mais ativas. Veja:

![image](https://user-images.githubusercontent.com/304759/157197489-24b227e7-0a8b-4060-b9fc-967a51ef358f.png)

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
As etapas desativadas, e os tipos de prorrogações associadas a essas etapas, foram filtrados para não aparecem nas comboboxes

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Havia um erro no teste phase_spec, que causava uma falha intermitente na execução do rake, dependendo da semente aleatória usada. Ao limpar registros para fazer um teste em um método, não era feita a limpeza de outros possíveis registros que poderiam depender da existência desses primeiros
