### ISSUE TITLE
Criar uma variável reply_to para escolha de um remetente para os emails automáticos

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#405]
Quando o SAPOS envia um email automático, caso a pessoa responda, esse email se perde. Seria desejável poder configurar um email de _reply_to_, podendo do ser uma variável na tela de variáveis

**Comment by leomurta** [comment]
@JoaoFelipe , imagino que isso seja fácil de fazer. Depois que finalizar a migração das libs, poderia dar uma olhada nisso? Os e-mails não estão mais se perdendo, mas todos chegam para mim, mesmo os que são de outros programas. Talvez, o ideal seria o reply_to ser o e-mail do admin da instância do Sapos.

**Comment by nataliacfUFF** [comment]
Oi, pessoal

Sugiro que encaminhem também com cópia para o e-mail da secretaria do
programa, pois geralmente são respostas para problemas acadêmicos que o
sapos reportou.

Abs,

Natalia

Em qui, 24 de ago de 2023 07:48, Leonardo Gresta Paulino Murta <
***@***.***> escreveu:

**Comment by IgorMonardez** [comment]
Bom dia pessoal, 
Caso o usuário responda algum e-mail automático do SAPOS, a mensagem seria enviada para esse e-mail reply_to, correto?

**Comment by JoaoFelipe** [comment]
Isso

**Comment by IgorMonardez** [comment]
Qual seria o email do admin da instância do SAPOS?

**Comment by leomurta** [comment]
Não sei se entendi bem a pergunta, mas vamos lá: como não sabemos como será a instalação do Sapos por cada usuário, é necessário pensarmos numa solução um pouco independente da instância. Na instância do IC, todos os e-mails enviados pelo Sapos saem como sapos@ic.uff.br. Quando alguém responde a esses e-mails (o que pedimos para não ser feito), chega para mim, independentemente da instância (temos 4 em operação nesse momento). Aí eu encaminho para a coordenação do respectivo programa. A ideia é ter um reply-to que usa o e-mail configurado nas variáveis de cada instância para direcionar as respostas. Assim, cada programa decide quem deve receber eventuais respostas a esse e-mail (secretaria, coordenação, etc.)

**Comment by leomurta** [comment]
Pessoal, como está o andamento dessa issue? Mandei um e-mail para vcs sugerindo uma mudança no nosso Workflow, para termos mais visibilidade.

**Comment by IgorMonardez** [comment]
Eu estou ajustando alguns detalhes e tentando emitir a notificação no meu sistema local, como forma de teste

**Comment by JoaoFelipe** [comment]
O PR parece ok pra mim. @leomurta pode colocar em homologação

(Precisamos fazer alguma coisa para isso? Ex: merge em bugfixes)

**Comment by leomurta** [comment]
@JoaoFelipe , acho que o ideal é vc ser o gatekeeper, então vc controla a entrada de código no master e no bugfixes, fazendo o merge quando estiver ok. Aí vc me fala qual ramo colocar em homologação. Combinei com a @braganholo de nos ajudar testando.

Se a feature ou correção for secundária, vc pode deixar acumular algumas no ramo antes de me pedir para jogar para homologação. Fica a seu critério.

**Comment by JoaoFelipe** [comment]
Merge feito. Acho que pode já colocar em homologação, mesmo que não homologue agora: se tiver alguma notificação automatica, já conseguimos pegar para verificar se o reply_to está certo. Também podemos forçar uma notificação, mas dá um pouco mais de trabalho de cadastrar.

**Comment by leomurta** [comment]
Coloquei em homologação. Testei tanto disparando uma notificação na mão quanto trocando a nota de um aluno. Em ambos os casos os e-mails chegaram e o header de reply-to veio certo. Ao clicar em reply no gmail, ele usou o e-mail do reply-to. Acha que é necessário aguardar pelo timer de notificação? Alguma chance de ter introduzido bug lá? Ou posso colocar em produção?

**Comment by IgorMonardez** [comment]
Melhor aguardar, apesar de aparentemente eu não ter modificado em nada
relacionado a timer de notificação, por não conhecer o sistema muito bem
pode ter feito alguma alteração indesejada.
*Igor Monárdez*


*Estudante de Ciência da Computação UFF *


Em ter., 28 de mai. de 2024 às 14:32, Leonardo Gresta Paulino Murta <
***@***.***> escreveu:

**Comment by JoaoFelipe** [comment]
Acho improvável dar erro com o timer, já que funcionou disparando na mão, mas como esse reply_to não é uma necessidade urgente, acho que dá pra esperar (ou cadastrar uma notificação para amanhã e já verificar isso)

**Comment by leomurta** [comment]
A gente espera. Na virada do mês sempre vem alguma notificação.

**Comment by leomurta** [comment]
Deu tudo certo na homologação. Passei para produção.
