### ISSUE TITLE
Ajustes na lista de disciplinas do semestre

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/sapos#441]
Criando essa issue para os 3 ajustes que precisam ser feitos:

- [x] Exibir todos os horários da disciplina quando há mais de um horário por dia no **quadro de horários (pdf)**
- [x] Exibir todos os horários da disciplina quando há mais de um horário por dia na **página de inscrição**
- [x] Esconder disciplinas já cursadas na **página de inscrição** quando não houver possibilidade de pegar a disciplina mais de uma vez

**Comment by JoaoFelipe** [comment]
@leomurta Pode colocar bugfixes em homologação. Resolvi a #398 também

**Comment by leomurta** [comment]
Feito João. Está em homologação. Pode dar uma verificada, por favor?

Em sáb., 19 de ago. de 2023 às 04:22, João Felipe N. Pimentel <
***@***.***> escreveu:

**Comment by JoaoFelipe** [comment]
Parece tudo ok

**Comment by leomurta** [comment]
Coloquei em produção. Obrigado João.

Em seg., 21 de ago. de 2023 às 22:27, João Felipe N. Pimentel <
***@***.***> escreveu:
