### ISSUE TITLE
Sugestão de pequenas alterações na logomarca do SAPOS

### ISSUE THREAD

**Issue by maiquelfx** [gems-uff/sapos#460]
Prezados,

Bom dia!

Sou estudante do Mestrado em Computação na UFF e um apaixonado por design e tecnologia. Ao observar a logo do SAPOS, que é excelente por sinal, percebi que poderiam ser feitas algumas mudanças em prol de uma marca um pouco mais robusta e atualizada.

Fiz cerca de 10 alterações e separei 4 que considero interessantes. Entre essas alterações estão um leve efeito 3D na pata que segura o mouse, adicionei detalhes extras no mouse e sugeri um mouse mais moderno, estilo "mouse gamer".

Acredito que a fonte poderia ser algo que remeta melhor à área de tecnologia, e as cores poderiam ser variações em verde que se aproximem da logo do Instituto de Computação.

O projeto está em Corel Draw vetorizado. Caso a sugestão seja aceita, estou disponível para enviar os arquivos JPG, PNG, CDR e EPS com nome das fontes e paleta de cores RGB/CMYK/HEX para serem anexados ao projeto.

Agradeço pela atenção e aguardo um retorno.
![sapos](https://github.com/gems-uff/sapos/assets/144914257/ec0a6a65-caa0-4841-b90c-649bd8b1d550)
![sapos1](https://github.com/gems-uff/sapos/assets/144914257/f76431a6-7f50-4496-9546-de6724d1204d)

Atenciosamente,
Maiquel Gomes
21 97651-9534
maiquelfx@gmail.com

**Comment by leomurta** [comment]
Maiquel,

Obrigado pela contribuição. Eu confesso que prefiro algo mais leve, como o atual. Dentro das suas sugestões, os que mais gostei são as variações 1 e 2. Vamos ver o que os demais contribuidores do projeto acham.

Leo

**Comment by braganholo** [comment]
Oi Maiquel

Muito obrigada pela contribuição! Eu confesso que gosto mais do logo atual.
Em especial, a cor atual me agrada mais.

Vanessa

**Comment by leomurta** [comment]
Pessoal, como ninguém apoiou a mudança, vou fechar essa issue. De qq forma, muito obrigado pela sugestão, Maiquel!
