### ISSUE TITLE
Erro em inscrições - campo referente a aluno ou disciplina desaparecem da tela

### ISSUE THREAD

**Issue by braganholo** [gems-uff/sapos#47]
O erro acontece na tela de turmas ou na tela de matrículas. Às vezes, o campo referente ao aluno some da tela de turma (e fica apenas os campos de disciplina, situação, nota, frequencia e obs). Da mesma forma que isso some, depois volta, sem que ninguém modifique nada no código. Na tela de matrícula, quem some é o campo de disciplina, conforme tela abaixo.

![image](https://f.cloud.github.com/assets/1494494/933133/56528826-0050-11e3-8fde-fb78f5464ab9.png)

Já notamos que quando o aluno some da tela de turma, se sairmos da tela, formos até a tela de inscrição, adicionarmos uma inscrição e depois voltarmos para tela de turma, os alunos reaparecem. Mas não sabemos explicar o motivo.

**Comment by leomurta** [comment]
Vou fechar essa issue pois com o tratamento da issue #167 isso pode ter sido resolvido.

**Comment by braganholo** [comment]
Aparentemente está ok. Se voltar a ocorrer, reabro.

**Comment by braganholo** [comment]
Esse cara é persistente... acabo de perceber que ele não foi corrigido.

**Comment by leomurta** [comment]
Continua aparecendo esse bug?

**Comment by braganholo** [comment]
Sim, de forma intermitente como sempre.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
No meu ambiente de desenvolvimento, o bug acontece na tela de edição de turmas. Ainda não vi o erro acontecer na tela de matrículas, mas estou fazendo alguns testes para ver se ele aparece. 

Para fazer o erro aparecer na tela de turmas, sigo os seguintes passos: 

Considerando que existam uma matrícula m1 e uma turma t1 cadastrados,
de modo que m1 não esteja inscrita na t1.

Inscrever m1 em t1 da seguinte forma:

Em Alunos -> Matrículas, escolher a m1 para editar.  

Na tela de edição da m1, inscrever ela na t1, com situação incompleto e clicar no botão atualizar.

Em Disciplinas -> Turmas, escolher a t1 para editar.

Neste momento, na tela de edição de t1, em inscrições, a coluna matrícula não aparece.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Olá. Segui fazendo alguns testes no meu ambiente.

Na tela de turmas o bug acontece quando o objeto Thread.current[:constraint_columns] guarda um hash com chave e valor: "class_enrollment-subform"=>[:enrollment]

Quando esse valor :enrollment existe, o active_scaffold não renderiza a coluna de matrícula na tela de edição de turma. Após alguns minutos, o valor é removido automaticamente do objeto Thread.current[:constraint_columns] e o active_scaffold passa a renderizar a coluna de matrícula.  

Limpando o valor no before_action da tela de edição de turma aparentemente resolve o problema
para essa tela.   

Na tela de matrícula, ainda não pude ver o bug acontecendo. Ele ainda tem acontecido? 
No caso dessa tela, o active_scaffold renderizou a coluna matrícula mesmo com o valor
"class_enrollment-subform"=>[:enrollment] existindo no objeto Thread.current[:constraint_columns] .

**Comment by braganholo** [comment]
Sim Carlos, na tela de matrícula o bug ainda acontece. Entrei lá agora e aconteceu.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Oi Vanessa.
Sim, talvez fazer Thread.current[:constraint_columns]=nil no before_action da matrícula possa
ajudar. Você  lembra se foi na tela de adicionar ou editar matrícula? Gostaria de tentar causar
o mesmo bug, posso ver no ambiente de homologação e tentar causar ele no desenvolvimento.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Coloquei uma rotina na before_action na página de matrículas. Ainda não consegui ver se a modificação tem efeito porque não consegui causar o bug nas minhas tentativas. Talvez funcione. As telas de matrícula e turma já poderiam ser testadas.

**Comment by braganholo** [comment]
Carlos, até onde me lembro o bug é na tela de edição de matrícula. Esse seu fix seria para essa tela?

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
No fix coloquei o before_action para chamar a rotina antes das telas de edição, nova e exibição de matrícula. Se o bug acontece apenas na tela de edição, posso mudar a chamada para ele atuar apenas nessa tela. Isso pode evitar possíveis efeitos colaterais.

**Comment by braganholo** [comment]
Faça isso então por favor e avise, aí colocamos em homologação pra testes.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Oi Vanessa, fiz a mudança. Também subi um commit para a issue #226

**Comment by leomurta** [comment]
Coloquei o ramo bugfixes em homologação.

2017-07-14 18:22 GMT-03:00 Carlos-Eduardo-Cabral-da-Cunha <
notifications@github.com>:

**Comment by braganholo** [comment]
Esse bug é brasileiro: não desiste nunca! Ele voltou, infelizmente.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Ele é highlander. Aconteceu em homologação?

**Comment by braganholo** [comment]
Não. O Helio me relatou o erro hoje. Aconteceu em produção.

**Comment by leomurta** [comment]
Passaram 6 anos e nesse período as libs tiveram muitas atualizações. Esse erro ainda acontece? Vou perguntar na secretaria.

**Comment by leomurta** [comment]
Aparentemente o defeito foi corrigido com a atualização de alguma lib. Vou fechar. Se voltar, reabrimos.
